//! Machine-readable catalog of the whole CLI surface, generated by walking
//! the clap command tree so it can never drift from the real interface.

use anyhow::Result;
use clap::builder::Command as ClapCommand;
use clap::{Arg, ArgAction, Args, CommandFactory, ValueEnum};
use serde_json::{Value, json};

use super::args::OutputFormat;

#[derive(Clone, Copy, Debug, ValueEnum)]
enum CapabilitiesSchemaVersion {
    #[value(name = "1")]
    V1,
    #[value(name = "2")]
    V2,
    #[value(name = "3")]
    V3,
}

impl CapabilitiesSchemaVersion {
    const fn number(self) -> u8 {
        match self {
            Self::V1 => 1,
            Self::V2 => 2,
            Self::V3 => 3,
        }
    }

    /// Reports whether this version carries the per-dialect support matrix.
    const fn includes_dialect_contract(self) -> bool {
        matches!(self, Self::V2 | Self::V3)
    }
}

#[derive(Debug, Args)]
pub(super) struct CapabilitiesArgs {
    /// Output format. Defaults to json: this command exists for agent discovery.
    #[arg(long, value_enum, default_value_t = OutputFormat::Json)]
    pub(super) output: OutputFormat,

    /// Machine-readable schema version.
    #[arg(long, value_enum, default_value = "1")]
    schema_version: CapabilitiesSchemaVersion,
}

pub(super) fn capabilities(args: CapabilitiesArgs) -> Result<()> {
    // Built, not merely constructed: `clap` copies a `global = true` argument
    // into each subcommand during `build`, and an unbuilt tree would publish a
    // catalogue missing the flags that apply everywhere.
    let mut root = super::Cli::command();
    root.build();
    let root = root;
    match args.output {
        OutputFormat::Json => {
            let mut report = json!({
                "schema_version": args.schema_version.number(),
                "name": root.get_name(),
                "version": root.get_version(),
                "about": about_text(&root),
                "commands": subcommand_reports(&root, args.schema_version),
            });
            if args.schema_version.includes_dialect_contract() {
                report["dialect_contract"] =
                    super::contract::dialect_contract_report(args.schema_version.number());
            }
            println!("{}", serde_json::to_string_pretty(&report)?);
        }
        OutputFormat::Text => {
            let mut lines = Vec::new();
            render_text(&root, &mut Vec::new(), &mut lines);
            println!("{}", lines.join("\n"));
        }
    }
    Ok(())
}

fn subcommand_reports(
    command: &ClapCommand,
    schema_version: CapabilitiesSchemaVersion,
) -> Vec<Value> {
    command
        .get_subcommands()
        .filter(|subcommand| subcommand.get_name() != "help")
        .map(|subcommand| {
            let nested = subcommand_reports(subcommand, schema_version);
            let mut report = json!({
                "name": subcommand.get_name(),
                "about": about_text(subcommand),
                "args": argument_reports(subcommand, schema_version),
            });
            if let Some(gates) = gate_reports(subcommand) {
                report["gates"] = gates;
            }
            if !nested.is_empty() {
                report["commands"] = Value::Array(nested);
            }
            report
        })
        .collect()
}

fn argument_reports(
    command: &ClapCommand,
    schema_version: CapabilitiesSchemaVersion,
) -> Vec<Value> {
    command
        .get_arguments()
        .filter(|arg| {
            !matches!(
                (arg.get_id().as_str(), schema_version),
                ("help" | "version", _) | ("schema_version", CapabilitiesSchemaVersion::V1)
            )
        })
        .map(|arg| {
            json!({
                "id": arg.get_id().as_str(),
                "long": arg.get_long(),
                "short": arg.get_short().map(String::from),
                "kind": argument_kind(arg),
                "help": arg.get_help().map(ToString::to_string),
                "required": arg.is_required_set(),
                "repeatable": is_repeatable(arg),
                "value_names": arg
                    .get_value_names()
                    .map(|names| names.iter().map(ToString::to_string).collect::<Vec<_>>()),
                "default_values": default_values(arg),
                "possible_values": possible_values(arg),
            })
        })
        .collect()
}

/// How a gate flag decides to fail.
///
/// Derived from the flag's name rather than declared, because with ninety-odd
/// gate flags across 275 commands a hand-kept table would be wrong within a
/// release. The naming convention *is* the unification — a flag that follows
/// it is discoverable, and a contract test refuses one that does not.
/// The convention, stated once:
///
/// | Spelling | Kind | Fails when |
/// | --- | --- | --- |
/// | `--fail-on <severity>` | `severity` | a finding at or above the level |
/// | `--fail-on-<thing>` | `presence` | any `<thing>` was found |
/// | `--require-<thing> <N>` | `minimum` | fewer than `N` were found |
///
/// A `--require-*` that takes no value is deliberately *not* a gate:
/// `--require-suppression-reason` changes what counts as an unused
/// suppression rather than deciding the exit status, and reporting it as a
/// gate would tell a caller it can fail on something it cannot.
fn gate_kind(arg: &Arg) -> Option<&'static str> {
    let long = arg.get_long()?;
    // Order matters: the prefix test would swallow the exact match.
    if long == "fail-on" {
        return Some("severity");
    }
    if long.starts_with("fail-on-") {
        return Some("presence");
    }
    if long.starts_with("require-") && takes_value(arg) {
        return Some("minimum");
    }
    None
}

/// The gates one command offers, or `None` when it has none.
///
/// Absent rather than empty so "this command cannot fail on a policy" and
/// "we did not look" stay distinguishable.
fn gate_reports(command: &ClapCommand) -> Option<Value> {
    let gates: Vec<Value> = command
        .get_arguments()
        .filter_map(|arg| {
            let kind = gate_kind(arg)?;
            Some(json!({
                "flag": format!("--{}", arg.get_long()?),
                "kind": kind,
                "help": arg.get_help().map(ToString::to_string),
                "exit_code": paredit_core_cli::gate::GATE_FAILURE_EXIT_CODE,
            }))
        })
        .collect();
    (!gates.is_empty()).then_some(Value::Array(gates))
}

fn argument_kind(arg: &Arg) -> &'static str {
    if arg.is_positional() {
        "positional"
    } else if takes_value(arg) {
        "option"
    } else {
        "flag"
    }
}

fn takes_value(arg: &Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Set | ArgAction::Append)
}

fn is_repeatable(arg: &Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Append | ArgAction::Count)
        || arg
            .get_num_args()
            .is_some_and(|range| range.max_values() > 1)
}

fn default_values(arg: &Arg) -> Vec<String> {
    arg.get_default_values()
        .iter()
        .map(|value| value.to_string_lossy().into_owned())
        .collect()
}

fn possible_values(arg: &Arg) -> Option<Vec<String>> {
    let values = arg
        .get_possible_values()
        .iter()
        .map(|value| value.get_name().to_owned())
        .collect::<Vec<_>>();
    (!values.is_empty()).then_some(values)
}

fn about_text(command: &ClapCommand) -> Option<String> {
    command.get_about().map(ToString::to_string)
}

fn render_text(command: &ClapCommand, prefix: &mut Vec<String>, lines: &mut Vec<String>) {
    for subcommand in command.get_subcommands() {
        if subcommand.get_name() == "help" {
            continue;
        }

        prefix.push(subcommand.get_name().to_owned());
        let about = about_text(subcommand).unwrap_or_default();
        lines.push(format!("paredit {}  {}", prefix.join(" "), about));
        for arg in subcommand.get_arguments() {
            if matches!(arg.get_id().as_str(), "help" | "version") {
                continue;
            }
            lines.push(format!("  {}", render_arg(arg)));
        }
        render_text(subcommand, prefix, lines);
        prefix.pop();
    }
}

fn render_arg(arg: &Arg) -> String {
    let name = match (arg.get_long(), arg.is_positional()) {
        (Some(long), _) => format!("--{long}"),
        (None, true) => format!("<{}>", arg.get_id().as_str().to_uppercase()),
        (None, false) => arg.get_id().to_string(),
    };
    let value = if takes_value(arg) {
        arg.get_value_names()
            .and_then(|names| names.first().map(|value_name| format!(" <{value_name}>")))
            .unwrap_or_else(|| " <VALUE>".to_owned())
    } else {
        String::new()
    };
    let help = arg
        .get_help()
        .map(|help| format!("  {help}"))
        .unwrap_or_default();
    format!("{name}{value}{help}")
}
