//! Core Lisp parsing, dialect, and semantic refactoring rules that stay
//! independent from CLI delivery and filesystem adapters.

// Phase 1 facade (section 4.1). These modules now live in
// `paredit-core-syntax`; re-exporting them here keeps every existing
// `crate::domain::<module>` path and the public `paredit_cli::domain::…`
// API working unchanged, so the split can proceed one package at a time.
//
// Visibility mirrors the original `mod` declarations exactly - promoting a
// `pub(crate)` module to `pub` here would silently widen the public API.
pub use paredit_core_syntax::{common_lisp, definition, dialect, form_shape, sexpr};
// Phase 3 facade: benches/similarity_report.rs uses the public library API.
pub(crate) use paredit_core_syntax::{expression_equality, graph, leading_trivia, view_query};
pub use paredit_feature_extract::extract_constant::domain as extract_constant;
pub use paredit_feature_extract::extract_function::domain as extract_function;
pub use paredit_feature_extract::extract_local_function::domain as extract_local_function;
pub use paredit_feature_form_transform::replace_forms::domain as replace_forms;
pub use paredit_feature_form_transform::sort_definitions::domain as sort_definitions;
pub use paredit_feature_form_transform::split_file::domain as split_file;
pub use paredit_feature_form_transform::thread_expression::domain as thread_expression;
pub use paredit_feature_form_transform::unthread_expression::domain as unthread_expression;
pub use paredit_feature_form_transform::unwrap_call::domain as unwrap_call;
pub use paredit_feature_inline::inline_function::domain as inline_function;
pub use paredit_feature_inline::inline_lambda::domain as inline_lambda;
pub use paredit_feature_inline::inline_let::domain as inline_let;
pub use paredit_feature_inline::inline_local_function::domain as inline_local_function;
pub use paredit_feature_inline::inline_symbol_macro::domain as inline_symbol_macro;
pub use paredit_feature_similarity::duplicate_report::domain as duplicate_report;
pub use paredit_feature_similarity::form_similarity;
pub use paredit_feature_similarity::similarity_report::domain as similarity_report;

// Phase 2 facade (section 4.1), visibility mirroring the original `mod` lines.
pub(crate) use paredit_core_edit::{convert_control, extract_shared, mutation_safety};
pub use paredit_core_edit::{refactor_execute, refactor_plan, refactor_preview};
pub use paredit_core_semantics::lexical_scope;
pub(crate) use paredit_core_semantics::{callable_scope, definition_reference, semantics};

pub mod accessor_arity_report;
pub mod append_list_to_cons_report;
pub mod append_nil_report;
pub mod binds_constant_report;
pub mod butlast_default_count_report;
pub mod call_cycle_report;
pub mod call_graph_report;
pub mod call_report;
pub mod car_nthcdr_report;
pub mod car_reverse_report;
pub mod case_nil_key_report;
pub mod char_case_fold_report;
pub mod char_op_string_report;
pub mod class_cycle_report;
pub mod code_char_char_code_report;
pub mod coerce_to_t_report;
pub mod complexity_report;
pub mod cond_t_clause_report;
pub(crate) mod conditional_sugar;
pub mod cons_to_list_report;
pub mod constant_if_test_report;
pub mod constant_when_test_report;
pub mod de_morgan_report;
pub mod dead_boolean_operand_report;
pub mod definition_report;
pub mod defpackage_quoted_report;
pub mod dependency_report;
pub mod destructive_literal_report;
pub mod double_reverse_report;
pub mod duplicate_boolean_operand_report;
pub mod duplicate_case_key_report;
pub mod duplicate_cond_test_report;
pub mod duplicate_export_report;
pub mod duplicate_keyword_report;
pub mod duplicate_lambda_list_keyword_report;
pub mod duplicate_let_binding_report;
pub mod duplicate_method_report;
pub mod duplicate_parameter_report;
pub mod duplicate_setf_place_report;
pub mod duplicate_slot_report;
pub mod empty_body_report;
pub mod empty_let_report;
pub mod eq_char_comparison_report;
pub mod eq_number_comparison_report;
pub mod eql_list_comparison_report;
pub mod eql_search_literal_report;
pub mod eql_string_comparison_report;
pub mod equality_arity_report;
pub mod eval_when_situation_report;
pub mod exhaustive_case_otherwise_report;
pub mod explicit_nil_return_report;
pub mod explicit_step_delta_report;
pub mod form_report;
pub mod format_missing_destination_report;
pub mod format_newline_report;
pub mod format_to_string_report;
pub mod funcall_lambda_report;
pub(crate) mod function_parameter;
pub mod getf_default_nil_report;
pub mod gethash_default_report;
pub mod handler_case_no_clauses_report;
pub mod identical_if_branch_report;
pub mod identity_arithmetic_report;
pub mod if_arity_report;
pub mod if_not_report;
pub mod if_to_or_report;
pub mod if_to_unless_report;
pub mod impact_report;
pub(crate) mod inline_literal_constant;
pub mod lambda_list_keyword_order_report;
pub mod last_default_count_report;
pub(crate) mod lint;
pub mod lint_report;
pub mod lint_suppression;
pub mod list_star_nil_report;
pub mod list_star_to_cons_report;
pub mod literal_place_report;
pub mod make_array_default_keyword_report;
pub mod make_hash_table_test_report;
pub mod make_list_default_element_report;
pub mod malformed_case_clause_report;
pub mod malformed_cond_clause_report;
pub mod malformed_iteration_spec_report;
pub mod malformed_let_binding_report;
pub mod manual_incf_report;
pub mod manual_push_report;
pub mod manual_pushnew_report;
pub mod modify_macro_arity_report;
pub mod multiple_value_list_of_values_report;
pub mod naming_report;
pub mod negated_comparison_report;
pub mod negated_if_report;
pub mod negated_step_delta_report;
pub mod negated_when_unless_report;
pub mod nested_boolean_report;
pub mod nested_char_case_report;
pub mod nested_cxr_report;
pub mod nested_progn_report;
pub mod nested_string_case_report;
pub mod nested_unless_report;
pub mod nested_when_report;
pub mod nil_comparison_report;
pub mod nth_constant_index_report;
pub mod nthcdr_small_index_report;
pub mod nthcdr_zero_report;
pub mod one_armed_if_report;
pub mod one_step_arithmetic_report;
pub(crate) mod package;
pub mod package_boundary_report;
pub mod package_conflict_report;
pub mod package_cycle_report;
pub mod package_report;
pub mod parse_integer_default_radix_report;
pub mod prog2_to_progn_report;
pub mod quoted_case_key_report;
pub mod reachability_report;
pub mod redefinition_report;
pub mod redundant_apply_report;
pub mod redundant_body_progn_report;
pub mod redundant_boolean_identity_report;
pub mod redundant_count_nil_report;
pub mod redundant_divisor_report;
pub mod redundant_end_nil_report;
pub mod redundant_eql_test_report;
pub mod redundant_from_end_nil_report;
pub mod redundant_funcall_report;
pub mod redundant_identity_key_report;
pub mod redundant_identity_report;
pub mod redundant_if_nil_report;
pub mod redundant_let_star_report;
pub mod redundant_prog1_report;
pub mod redundant_progn_report;
pub mod redundant_quote_report;
pub mod redundant_start_zero_report;
pub mod redundant_the_report;
pub(crate) mod remove_unused_binding;
pub(crate) mod remove_unused_control;
pub(crate) mod remove_unused_definition;
pub mod rename;
pub(crate) mod rename_control;
mod rename_types;
pub mod report_policy;
pub mod self_assignment_report;
pub mod self_comparison_report;
pub mod setf_arity_report;
pub mod setq_non_variable_report;
pub mod shadowed_binding_report;
pub mod sharp_quoted_lambda_report;
pub mod sign_comparison_report;
pub mod signature_report;
pub mod single_arg_comparison_report;
pub mod single_clause_cond_report;
pub mod single_operand_arithmetic_report;
pub mod single_operand_boolean_report;
pub mod single_operand_list_op_report;
pub mod single_value_bind_report;
pub mod step_zero_report;
pub mod string_case_fold_report;
pub mod struct_cycle_report;
pub mod subseq_zero_report;
pub mod system_conflict_report;
pub mod system_cycle_report;
pub(crate) mod system_order;
pub mod t_comparison_report;
pub mod the_arity_report;
pub mod typecase_nil_key_report;
pub mod typep_predicate_report;
pub mod undefined_package_report;
pub mod unreachable_case_clause_report;
pub mod unreachable_cond_clause_report;
pub mod unused_export_report;
pub mod unused_local_callable_report;
pub mod unused_nickname_report;
pub mod unused_package_report;
pub mod unused_parameter_report;
pub mod unwind_protect_no_cleanup_report;
pub mod values_list_of_list_report;
pub mod verbose_negation_report;
pub mod workspace_report;
pub mod zero_divisor_report;

// Facade re-exports for extracted feature packages (section 4.1).
pub use paredit_feature_binding::convert_sequential_binding::domain as convert_sequential_binding;
pub use paredit_feature_binding::introduce_let::domain as introduce_let;
pub use paredit_feature_binding::let_report::domain as let_report;
