//! Core Lisp parsing, dialect, and semantic refactoring rules that stay
//! independent from CLI delivery and filesystem adapters.

// Phase 1 facade (section 4.1). These modules now live in
// `paredit-core-syntax`; re-exporting them here keeps every existing
// `crate::domain::<module>` path and the public `paredit_cli::domain::…`
// API working unchanged, so the split can proceed one package at a time.
//
// Visibility mirrors the original `mod` declarations exactly - promoting a
// `pub(crate)` module to `pub` here would silently widen the public API.
pub use paredit_core_syntax::{common_lisp, definition, dialect, form_shape, sexpr};
// Phase 3 facade: benches/similarity_report.rs uses the public library API.
pub(crate) use paredit_core_syntax::view_query;
pub use paredit_feature_extract::extract_constant::domain as extract_constant;
pub use paredit_feature_extract::extract_function::domain as extract_function;
pub use paredit_feature_extract::extract_local_function::domain as extract_local_function;
pub use paredit_feature_form_transform::replace_forms::domain as replace_forms;
pub use paredit_feature_form_transform::sort_definitions::domain as sort_definitions;
pub use paredit_feature_form_transform::split_file::domain as split_file;
pub use paredit_feature_form_transform::thread_expression::domain as thread_expression;
pub use paredit_feature_form_transform::unthread_expression::domain as unthread_expression;
pub use paredit_feature_form_transform::unwrap_call::domain as unwrap_call;
pub use paredit_feature_inline::inline_function::domain as inline_function;
pub use paredit_feature_inline::inline_lambda::domain as inline_lambda;
pub use paredit_feature_inline::inline_let::domain as inline_let;
pub use paredit_feature_inline::inline_local_function::domain as inline_local_function;
pub use paredit_feature_inline::inline_symbol_macro::domain as inline_symbol_macro;
pub use paredit_feature_similarity::duplicate_report::domain as duplicate_report;
pub use paredit_feature_similarity::form_similarity;
pub use paredit_feature_similarity::similarity_report::domain as similarity_report;

// Phase 2 facade (section 4.1), visibility mirroring the original `mod` lines.
pub use paredit_core_edit::{refactor_execute, refactor_plan, refactor_preview};
pub use paredit_core_semantics::lexical_scope;
pub(crate) use paredit_core_semantics::semantics;

pub mod duplicate_export_report;
pub mod duplicate_method_report;
pub mod duplicate_slot_report;
pub(crate) mod lint;
pub mod lint_report;
pub mod lint_suppression;
pub mod report_policy;
pub mod shadowed_binding_report;
pub mod unused_parameter_report;

// Facade re-exports for extracted feature packages (section 4.1).
pub use paredit_feature_inline::inline_literal_constant::domain as inline_literal_constant;
pub use paredit_feature_conditional_conversion::conditional_sugar::domain as conditional_sugar;
pub use paredit_feature_binding::convert_sequential_binding::domain as convert_sequential_binding;
pub use paredit_feature_binding::introduce_let::domain as introduce_let;
pub use paredit_feature_binding::let_report::domain as let_report;
pub use paredit_feature_function_parameter::function_parameter::domain as function_parameter;
pub use paredit_feature_lint_conditional::case_nil_key::domain as case_nil_key_report;
pub use paredit_feature_lint_conditional::cond_t_clause::domain as cond_t_clause_report;
pub use paredit_feature_lint_conditional::constant_if_test::domain as constant_if_test_report;
pub use paredit_feature_lint_conditional::constant_when_test::domain as constant_when_test_report;
pub use paredit_feature_lint_conditional::de_morgan::domain as de_morgan_report;
pub use paredit_feature_lint_conditional::dead_boolean_operand::domain as dead_boolean_operand_report;
pub use paredit_feature_lint_conditional::duplicate_boolean_operands::domain as duplicate_boolean_operand_report;
pub use paredit_feature_lint_conditional::duplicate_case_keys::domain as duplicate_case_key_report;
pub use paredit_feature_lint_conditional::duplicate_cond_tests::domain as duplicate_cond_test_report;
pub use paredit_feature_lint_conditional::empty_body::domain as empty_body_report;
pub use paredit_feature_lint_conditional::exhaustive_case_otherwise::domain as exhaustive_case_otherwise_report;
pub use paredit_feature_lint_conditional::identical_if_branches::domain as identical_if_branch_report;
pub use paredit_feature_lint_conditional::if_arity::domain as if_arity_report;
pub use paredit_feature_lint_conditional::if_not::domain as if_not_report;
pub use paredit_feature_lint_conditional::if_to_or::domain as if_to_or_report;
pub use paredit_feature_lint_conditional::if_to_unless::domain as if_to_unless_report;
pub use paredit_feature_lint_conditional::malformed_case_clause::domain as malformed_case_clause_report;
pub use paredit_feature_lint_conditional::malformed_cond_clause::domain as malformed_cond_clause_report;
pub use paredit_feature_lint_conditional::negated_comparison::domain as negated_comparison_report;
pub use paredit_feature_lint_conditional::negated_if::domain as negated_if_report;
pub use paredit_feature_lint_conditional::negated_when_unless::domain as negated_when_unless_report;
pub use paredit_feature_lint_conditional::nested_boolean::domain as nested_boolean_report;
pub use paredit_feature_lint_conditional::nested_unless::domain as nested_unless_report;
pub use paredit_feature_lint_conditional::nested_when::domain as nested_when_report;
pub use paredit_feature_lint_conditional::one_armed_if::domain as one_armed_if_report;
pub use paredit_feature_lint_conditional::quoted_case_key::domain as quoted_case_key_report;
pub use paredit_feature_lint_conditional::redundant_boolean_identity::domain as redundant_boolean_identity_report;
pub use paredit_feature_lint_conditional::redundant_if_nil::domain as redundant_if_nil_report;
pub use paredit_feature_lint_conditional::single_clause_cond::domain as single_clause_cond_report;
pub use paredit_feature_lint_conditional::single_operand_boolean::domain as single_operand_boolean_report;
pub use paredit_feature_lint_conditional::typecase_nil_key::domain as typecase_nil_key_report;
pub use paredit_feature_lint_conditional::unreachable_case_clause::domain as unreachable_case_clause_report;
pub use paredit_feature_lint_conditional::unreachable_cond_clause::domain as unreachable_cond_clause_report;
pub use paredit_feature_lint_control_flow::binds_constant::domain as binds_constant_report;
pub use paredit_feature_lint_control_flow::eval_when_situation::domain as eval_when_situation_report;
pub use paredit_feature_lint_control_flow::explicit_nil_return::domain as explicit_nil_return_report;
pub use paredit_feature_lint_control_flow::handler_case_no_clauses::domain as handler_case_no_clauses_report;
pub use paredit_feature_lint_control_flow::malformed_iteration_spec::domain as malformed_iteration_spec_report;
pub use paredit_feature_lint_control_flow::nested_progn::domain as nested_progn_report;
pub use paredit_feature_lint_control_flow::prog2_to_progn::domain as prog2_to_progn_report;
pub use paredit_feature_lint_control_flow::redundant_body_progn::domain as redundant_body_progn_report;
pub use paredit_feature_lint_control_flow::redundant_prog1::domain as redundant_prog1_report;
pub use paredit_feature_lint_control_flow::redundant_progn::domain as redundant_progn_report;
pub use paredit_feature_lint_control_flow::unwind_protect_no_cleanup::domain as unwind_protect_no_cleanup_report;
pub use paredit_feature_lint_form_shape::butlast_default_count::domain as butlast_default_count_report;
pub use paredit_feature_lint_form_shape::coerce_to_t::domain as coerce_to_t_report;
pub use paredit_feature_lint_form_shape::defpackage_quoted::domain as defpackage_quoted_report;
pub use paredit_feature_lint_form_shape::duplicate_keyword::domain as duplicate_keyword_report;
pub use paredit_feature_lint_form_shape::duplicate_lambda_list_keyword::domain as duplicate_lambda_list_keyword_report;
pub use paredit_feature_lint_form_shape::duplicate_let_bindings::domain as duplicate_let_binding_report;
pub use paredit_feature_lint_form_shape::duplicate_parameters::domain as duplicate_parameter_report;
pub use paredit_feature_lint_form_shape::duplicate_setf_places::domain as duplicate_setf_place_report;
pub use paredit_feature_lint_form_shape::empty_let::domain as empty_let_report;
pub use paredit_feature_lint_form_shape::funcall_lambda::domain as funcall_lambda_report;
pub use paredit_feature_lint_form_shape::getf_default_nil::domain as getf_default_nil_report;
pub use paredit_feature_lint_form_shape::gethash_default::domain as gethash_default_report;
pub use paredit_feature_lint_form_shape::lambda_list_keyword_order::domain as lambda_list_keyword_order_report;
pub use paredit_feature_lint_form_shape::make_array_default_keyword::domain as make_array_default_keyword_report;
pub use paredit_feature_lint_form_shape::make_hash_table_test::domain as make_hash_table_test_report;
pub use paredit_feature_lint_form_shape::make_list_default_element::domain as make_list_default_element_report;
pub use paredit_feature_lint_form_shape::malformed_let_binding::domain as malformed_let_binding_report;
pub use paredit_feature_lint_form_shape::manual_incf::domain as manual_incf_report;
pub use paredit_feature_lint_form_shape::manual_push::domain as manual_push_report;
pub use paredit_feature_lint_form_shape::manual_pushnew::domain as manual_pushnew_report;
pub use paredit_feature_lint_form_shape::multiple_value_list_of_values::domain as multiple_value_list_of_values_report;
pub use paredit_feature_lint_form_shape::nested_char_case::domain as nested_char_case_report;
pub use paredit_feature_lint_form_shape::nested_cxr::domain as nested_cxr_report;
pub use paredit_feature_lint_form_shape::parse_integer_default_radix::domain as parse_integer_default_radix_report;
pub use paredit_feature_lint_form_shape::redundant_apply::domain as redundant_apply_report;
pub use paredit_feature_lint_form_shape::redundant_funcall::domain as redundant_funcall_report;
pub use paredit_feature_lint_form_shape::redundant_identity::domain as redundant_identity_report;
pub use paredit_feature_lint_form_shape::redundant_let_star::domain as redundant_let_star_report;
pub use paredit_feature_lint_form_shape::redundant_quote::domain as redundant_quote_report;
pub use paredit_feature_lint_form_shape::redundant_the::domain as redundant_the_report;
pub use paredit_feature_lint_form_shape::self_assignment::domain as self_assignment_report;
pub use paredit_feature_lint_form_shape::setf_arity::domain as setf_arity_report;
pub use paredit_feature_lint_form_shape::setq_non_variable::domain as setq_non_variable_report;
pub use paredit_feature_lint_form_shape::sharp_quoted_lambda::domain as sharp_quoted_lambda_report;
pub use paredit_feature_lint_form_shape::single_value_bind::domain as single_value_bind_report;
pub use paredit_feature_lint_form_shape::the_arity::domain as the_arity_report;
pub use paredit_feature_lint_form_shape::typep_predicate::domain as typep_predicate_report;
pub use paredit_feature_lint_form_shape::values_list_of_list::domain as values_list_of_list_report;
pub use paredit_feature_lint_numeric::eq_char_comparison::domain as eq_char_comparison_report;
pub use paredit_feature_lint_numeric::eq_number_comparison::domain as eq_number_comparison_report;
pub use paredit_feature_lint_numeric::eql_list_comparison::domain as eql_list_comparison_report;
pub use paredit_feature_lint_numeric::eql_string_comparison::domain as eql_string_comparison_report;
pub use paredit_feature_lint_numeric::equality_arity::domain as equality_arity_report;
pub use paredit_feature_lint_numeric::explicit_step_delta::domain as explicit_step_delta_report;
pub use paredit_feature_lint_numeric::identity_arithmetic::domain as identity_arithmetic_report;
pub use paredit_feature_lint_numeric::literal_place::domain as literal_place_report;
pub use paredit_feature_lint_numeric::modify_macro_arity::domain as modify_macro_arity_report;
pub use paredit_feature_lint_numeric::negated_step_delta::domain as negated_step_delta_report;
pub use paredit_feature_lint_numeric::nil_comparison::domain as nil_comparison_report;
pub use paredit_feature_lint_numeric::one_step_arithmetic::domain as one_step_arithmetic_report;
pub use paredit_feature_lint_numeric::redundant_divisor::domain as redundant_divisor_report;
pub use paredit_feature_lint_numeric::self_comparison::domain as self_comparison_report;
pub use paredit_feature_lint_numeric::sign_comparison::domain as sign_comparison_report;
pub use paredit_feature_lint_numeric::single_arg_comparison::domain as single_arg_comparison_report;
pub use paredit_feature_lint_numeric::single_operand_arithmetic::domain as single_operand_arithmetic_report;
pub use paredit_feature_lint_numeric::step_zero::domain as step_zero_report;
pub use paredit_feature_lint_numeric::t_comparison::domain as t_comparison_report;
pub use paredit_feature_lint_numeric::verbose_negation::domain as verbose_negation_report;
pub use paredit_feature_lint_numeric::zero_divisor::domain as zero_divisor_report;
pub use paredit_feature_lint_sequence::accessor_arity::domain as accessor_arity_report;
pub use paredit_feature_lint_sequence::append_list_to_cons::domain as append_list_to_cons_report;
pub use paredit_feature_lint_sequence::append_nil::domain as append_nil_report;
pub use paredit_feature_lint_sequence::car_nthcdr::domain as car_nthcdr_report;
pub use paredit_feature_lint_sequence::car_reverse::domain as car_reverse_report;
pub use paredit_feature_lint_sequence::cons_to_list::domain as cons_to_list_report;
pub use paredit_feature_lint_sequence::destructive_literal::domain as destructive_literal_report;
pub use paredit_feature_lint_sequence::double_reverse::domain as double_reverse_report;
pub use paredit_feature_lint_sequence::eql_search_literal::domain as eql_search_literal_report;
pub use paredit_feature_lint_sequence::last_default_count::domain as last_default_count_report;
pub use paredit_feature_lint_sequence::list_star_nil::domain as list_star_nil_report;
pub use paredit_feature_lint_sequence::list_star_to_cons::domain as list_star_to_cons_report;
pub use paredit_feature_lint_sequence::nth_constant_index::domain as nth_constant_index_report;
pub use paredit_feature_lint_sequence::nthcdr_small_index::domain as nthcdr_small_index_report;
pub use paredit_feature_lint_sequence::nthcdr_zero::domain as nthcdr_zero_report;
pub use paredit_feature_lint_sequence::redundant_count_nil::domain as redundant_count_nil_report;
pub use paredit_feature_lint_sequence::redundant_end_nil::domain as redundant_end_nil_report;
pub use paredit_feature_lint_sequence::redundant_eql_test::domain as redundant_eql_test_report;
pub use paredit_feature_lint_sequence::redundant_from_end_nil::domain as redundant_from_end_nil_report;
pub use paredit_feature_lint_sequence::redundant_identity_key::domain as redundant_identity_key_report;
pub use paredit_feature_lint_sequence::redundant_start_zero::domain as redundant_start_zero_report;
pub use paredit_feature_lint_sequence::single_operand_list_op::domain as single_operand_list_op_report;
pub use paredit_feature_lint_sequence::subseq_zero::domain as subseq_zero_report;
pub use paredit_feature_lint_string_char::char_case_fold::domain as char_case_fold_report;
pub use paredit_feature_lint_string_char::char_op_string::domain as char_op_string_report;
pub use paredit_feature_lint_string_char::code_char_char_code::domain as code_char_char_code_report;
pub use paredit_feature_lint_string_char::format_missing_destination::domain as format_missing_destination_report;
pub use paredit_feature_lint_string_char::format_newline::domain as format_newline_report;
pub use paredit_feature_lint_string_char::format_to_string::domain as format_to_string_report;
pub use paredit_feature_lint_string_char::nested_string_case::domain as nested_string_case_report;
pub use paredit_feature_lint_string_char::string_case_fold::domain as string_case_fold_report;
pub use paredit_feature_package::dependency_report::domain as dependency_report;
pub use paredit_feature_package::package::domain as package;
pub use paredit_feature_package::package_boundary_report::domain as package_boundary_report;
pub use paredit_feature_package::package_conflict_report::domain as package_conflict_report;
pub use paredit_feature_package::package_report::domain as package_report;
pub use paredit_feature_package::system_conflict_report::domain as system_conflict_report;
pub use paredit_feature_package::unused_export_report::domain as unused_export_report;
pub use paredit_feature_package::unused_nickname_report::domain as unused_nickname_report;
pub use paredit_feature_package::unused_package_report::domain as unused_package_report;
pub use paredit_feature_project_analysis::call_cycle_report::domain as call_cycle_report;
pub use paredit_feature_project_analysis::call_graph_report::domain as call_graph_report;
pub use paredit_feature_project_analysis::call_report::domain as call_report;
pub use paredit_feature_project_analysis::class_cycle_report::domain as class_cycle_report;
pub use paredit_feature_project_analysis::complexity_report::domain as complexity_report;
pub use paredit_feature_project_analysis::form_report::domain as form_report;
pub use paredit_feature_project_analysis::impact_report::domain as impact_report;
pub use paredit_feature_project_analysis::naming_report::domain as naming_report;
pub use paredit_feature_project_analysis::package_cycle_report::domain as package_cycle_report;
pub use paredit_feature_project_analysis::reachability_report::domain as reachability_report;
pub use paredit_feature_project_analysis::redefinition_report::domain as redefinition_report;
pub use paredit_feature_project_analysis::signature_report::domain as signature_report;
pub use paredit_feature_project_analysis::struct_cycle_report::domain as struct_cycle_report;
pub use paredit_feature_project_analysis::system_cycle_report::domain as system_cycle_report;
pub use paredit_feature_project_analysis::system_order::domain as system_order;
pub use paredit_feature_project_analysis::undefined_package_report::domain as undefined_package_report;
pub use paredit_feature_project_analysis::unused_local_callable_report::domain as unused_local_callable_report;
pub use paredit_feature_project_analysis::workspace_report::domain as workspace_report;
pub use paredit_feature_remove_unused::definition_report::domain as definition_report;
pub use paredit_feature_remove_unused::remove_unused_binding::domain as remove_unused_binding;
pub use paredit_feature_remove_unused::remove_unused_control::domain as remove_unused_control;
pub use paredit_feature_remove_unused::remove_unused_definition::domain as remove_unused_definition;
pub use paredit_feature_rename::rename::domain as rename;
pub use paredit_feature_rename::rename_control::domain as rename_control;
pub use paredit_feature_rename::rename_types::domain as rename_types;
