//! The one place a lint rule is registered.
//!
//! `RULES`, `RULE_DOCS`, `FIXABLE_RULES`, and `WARNING_RULES` used to be four
//! hand-maintained parallel arrays that a new rule had to be threaded through
//! in lockstep. They are now derived from this array at compile time (see
//! [`catalog`]), so the only way to add a rule is to add its module and one
//! line here — and the only way for the catalogue to disagree with itself is
//! for the derivation to be wrong, which a `const` assertion catches.

pub mod catalog;

use super::rule::RuleEntry;

/// How many rules the suite ships. Pinned so that adding or losing a rule is a
/// deliberate, reviewed change rather than a silent drift in the catalogue.
pub const RULE_COUNT: usize = 134;

/// Every rule, in report order: findings are grouped by this order, and the
/// public `RULES`/`RULE_DOCS` arrays preserve it.
pub const REGISTRY: [RuleEntry; RULE_COUNT] = [
    RuleEntry::new(
        &paredit_feature_lint_form_shape::self_assignment::rule::META,
        &paredit_feature_lint_form_shape::self_assignment::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_setf_places::rule::META,
        &paredit_feature_lint_form_shape::duplicate_setf_places::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::setf_arity::rule::META,
        &paredit_feature_lint_form_shape::setf_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::setq_non_variable::rule::META,
        &paredit_feature_lint_form_shape::setq_non_variable::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_incf::rule::META,
        &paredit_feature_lint_form_shape::manual_incf::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_push::rule::META,
        &paredit_feature_lint_form_shape::manual_push::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_pushnew::rule::META,
        &paredit_feature_lint_form_shape::manual_pushnew::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::explicit_step_delta::rule::META,
        &paredit_feature_lint_numeric::explicit_step_delta::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::negated_step_delta::rule::META,
        &paredit_feature_lint_numeric::negated_step_delta::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::explicit_nil_return::rule::META,
        &paredit_feature_lint_control_flow::explicit_nil_return::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::cons_to_list::rule::META,
        &paredit_feature_lint_sequence::cons_to_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::double_reverse::rule::META,
        &paredit_feature_lint_sequence::double_reverse::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::modify_macro_arity::rule::META,
        &paredit_feature_lint_numeric::modify_macro_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_parameters::rule::META,
        &paredit_feature_lint_form_shape::duplicate_parameters::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_lambda_list_keyword::rule::META,
        &paredit_feature_lint_form_shape::duplicate_lambda_list_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::lambda_list_keyword_order::rule::META,
        &paredit_feature_lint_form_shape::lambda_list_keyword_order::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_quote::rule::META,
        &paredit_feature_lint_form_shape::redundant_quote::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_progn::rule::META,
        &paredit_feature_lint_control_flow::redundant_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::nested_progn::rule::META,
        &paredit_feature_lint_control_flow::nested_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_when::rule::META,
        &paredit_feature_lint_conditional::nested_when::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_unless::rule::META,
        &paredit_feature_lint_conditional::nested_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_boolean::rule::META,
        &paredit_feature_lint_conditional::nested_boolean::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::nested_cxr::rule::META,
        &paredit_feature_lint_form_shape::nested_cxr::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nth_constant_index::rule::META,
        &paredit_feature_lint_sequence::nth_constant_index::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nthcdr_zero::rule::META,
        &paredit_feature_lint_sequence::nthcdr_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nthcdr_small_index::rule::META,
        &paredit_feature_lint_sequence::nthcdr_small_index::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_body_progn::rule::META,
        &paredit_feature_lint_control_flow::redundant_body_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::empty_let::rule::META,
        &paredit_feature_lint_form_shape::empty_let::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::redundant_if_nil::rule::META,
        &paredit_feature_lint_conditional::redundant_if_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_let_star::rule::META,
        &paredit_feature_lint_form_shape::redundant_let_star::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_funcall::rule::META,
        &paredit_feature_lint_form_shape::redundant_funcall::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_the::rule::META,
        &paredit_feature_lint_form_shape::redundant_the::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::funcall_lambda::rule::META,
        &paredit_feature_lint_form_shape::funcall_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::sharp_quoted_lambda::rule::META,
        &paredit_feature_lint_form_shape::sharp_quoted_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_identity::rule::META,
        &paredit_feature_lint_form_shape::redundant_identity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_apply::rule::META,
        &paredit_feature_lint_form_shape::redundant_apply::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_eql_test::rule::META,
        &paredit_feature_lint_sequence::redundant_eql_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_identity_key::rule::META,
        &paredit_feature_lint_sequence::redundant_identity_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_when_unless::rule::META,
        &paredit_feature_lint_conditional::negated_when_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_comparison::rule::META,
        &paredit_feature_lint_conditional::negated_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_if::rule::META,
        &paredit_feature_lint_conditional::negated_if::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_to_or::rule::META,
        &paredit_feature_lint_conditional::if_to_or::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_not::rule::META,
        &paredit_feature_lint_conditional::if_not::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::one_step_arithmetic::rule::META,
        &paredit_feature_lint_numeric::one_step_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::one_armed_if::rule::META,
        &paredit_feature_lint_conditional::one_armed_if::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::self_comparison::rule::META,
        &paredit_feature_lint_numeric::self_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::nil_comparison::rule::META,
        &paredit_feature_lint_numeric::nil_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::t_comparison::rule::META,
        &paredit_feature_lint_numeric::t_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::identical_if_branches::rule::META,
        &paredit_feature_lint_conditional::identical_if_branches::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::constant_if_test::rule::META,
        &paredit_feature_lint_conditional::constant_if_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::constant_when_test::rule::META,
        &paredit_feature_lint_conditional::constant_when_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_arity::rule::META,
        &paredit_feature_lint_conditional::if_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::the_arity::rule::META,
        &paredit_feature_lint_form_shape::the_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::equality_arity::rule::META,
        &paredit_feature_lint_numeric::equality_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::accessor_arity::rule::META,
        &paredit_feature_lint_sequence::accessor_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::append_list_to_cons::rule::META,
        &paredit_feature_lint_sequence::append_list_to_cons::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_to_string::rule::META,
        &paredit_feature_lint_string_char::format_to_string::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_newline::rule::META,
        &paredit_feature_lint_string_char::format_newline::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::redundant_divisor::rule::META,
        &paredit_feature_lint_numeric::redundant_divisor::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_case_keys::rule::META,
        &paredit_feature_lint_conditional::duplicate_case_keys::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::quoted_case_key::rule::META,
        &paredit_feature_lint_conditional::quoted_case_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::case_nil_key::rule::META,
        &paredit_feature_lint_conditional::case_nil_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::typecase_nil_key::rule::META,
        &paredit_feature_lint_conditional::typecase_nil_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::malformed_case_clause::rule::META,
        &paredit_feature_lint_conditional::malformed_case_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::unreachable_case_clause::rule::META,
        &paredit_feature_lint_conditional::unreachable_case_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::exhaustive_case_otherwise::rule::META,
        &paredit_feature_lint_conditional::exhaustive_case_otherwise::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_cond_tests::rule::META,
        &paredit_feature_lint_conditional::duplicate_cond_tests::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::unreachable_cond_clause::rule::META,
        &paredit_feature_lint_conditional::unreachable_cond_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::malformed_cond_clause::rule::META,
        &paredit_feature_lint_conditional::malformed_cond_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_let_bindings::rule::META,
        &paredit_feature_lint_form_shape::duplicate_let_bindings::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::malformed_let_binding::rule::META,
        &paredit_feature_lint_form_shape::malformed_let_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::binds_constant::rule::META,
        &paredit_feature_lint_control_flow::binds_constant::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::malformed_iteration_spec::rule::META,
        &paredit_feature_lint_control_flow::malformed_iteration_spec::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::eval_when_situation::rule::META,
        &paredit_feature_lint_control_flow::eval_when_situation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_boolean_operands::rule::META,
        &paredit_feature_lint_conditional::duplicate_boolean_operands::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::dead_boolean_operand::rule::META,
        &paredit_feature_lint_conditional::dead_boolean_operand::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::redundant_boolean_identity::rule::META,
        &paredit_feature_lint_conditional::redundant_boolean_identity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::de_morgan::rule::META,
        &paredit_feature_lint_conditional::de_morgan::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::single_operand_boolean::rule::META,
        &paredit_feature_lint_conditional::single_operand_boolean::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::single_operand_list_op::rule::META,
        &paredit_feature_lint_sequence::single_operand_list_op::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::single_operand_arithmetic::rule::META,
        &paredit_feature_lint_numeric::single_operand_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eql_string_comparison::rule::META,
        &paredit_feature_lint_numeric::eql_string_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eql_list_comparison::rule::META,
        &paredit_feature_lint_numeric::eql_list_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::eql_search_literal::rule::META,
        &paredit_feature_lint_sequence::eql_search_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eq_number_comparison::rule::META,
        &paredit_feature_lint_numeric::eq_number_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eq_char_comparison::rule::META,
        &paredit_feature_lint_numeric::eq_char_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::single_arg_comparison::rule::META,
        &paredit_feature_lint_numeric::single_arg_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::sign_comparison::rule::META,
        &paredit_feature_lint_numeric::sign_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::single_clause_cond::rule::META,
        &paredit_feature_lint_conditional::single_clause_cond::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::cond_t_clause::rule::META,
        &paredit_feature_lint_conditional::cond_t_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::single_value_bind::rule::META,
        &paredit_feature_lint_form_shape::single_value_bind::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_missing_destination::rule::META,
        &paredit_feature_lint_string_char::format_missing_destination::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::literal_place::rule::META,
        &paredit_feature_lint_numeric::literal_place::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::destructive_literal::rule::META,
        &paredit_feature_lint_sequence::destructive_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::char_op_string::rule::META,
        &paredit_feature_lint_string_char::char_op_string::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::empty_body::rule::META,
        &paredit_feature_lint_conditional::empty_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::identity_arithmetic::rule::META,
        &paredit_feature_lint_numeric::identity_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::verbose_negation::rule::META,
        &paredit_feature_lint_numeric::verbose_negation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::list_star_to_cons::rule::META,
        &paredit_feature_lint_sequence::list_star_to_cons::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::values_list_of_list::rule::META,
        &paredit_feature_lint_form_shape::values_list_of_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_prog1::rule::META,
        &paredit_feature_lint_control_flow::redundant_prog1::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::subseq_zero::rule::META,
        &paredit_feature_lint_sequence::subseq_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::car_nthcdr::rule::META,
        &paredit_feature_lint_sequence::car_nthcdr::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::car_reverse::rule::META,
        &paredit_feature_lint_sequence::car_reverse::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::append_nil::rule::META,
        &paredit_feature_lint_sequence::append_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::multiple_value_list_of_values::rule::META,
        &paredit_feature_lint_form_shape::multiple_value_list_of_values::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::typep_predicate::rule::META,
        &paredit_feature_lint_form_shape::typep_predicate::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::coerce_to_t::rule::META,
        &paredit_feature_lint_form_shape::coerce_to_t::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::gethash_default::rule::META,
        &paredit_feature_lint_form_shape::gethash_default::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_hash_table_test::rule::META,
        &paredit_feature_lint_form_shape::make_hash_table_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::zero_divisor::rule::META,
        &paredit_feature_lint_numeric::zero_divisor::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_keyword::rule::META,
        &paredit_feature_lint_form_shape::duplicate_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::defpackage_quoted::rule::META,
        &paredit_feature_lint_form_shape::defpackage_quoted::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::step_zero::rule::META,
        &paredit_feature_lint_numeric::step_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_to_unless::rule::META,
        &paredit_feature_lint_conditional::if_to_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::prog2_to_progn::rule::META,
        &paredit_feature_lint_control_flow::prog2_to_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::handler_case_no_clauses::rule::META,
        &paredit_feature_lint_control_flow::handler_case_no_clauses::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::unwind_protect_no_cleanup::rule::META,
        &paredit_feature_lint_control_flow::unwind_protect_no_cleanup::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_start_zero::rule::META,
        &paredit_feature_lint_sequence::redundant_start_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_end_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_end_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_from_end_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_from_end_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_count_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_count_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::string_case_fold::rule::META,
        &paredit_feature_lint_string_char::string_case_fold::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::char_case_fold::rule::META,
        &paredit_feature_lint_string_char::char_case_fold::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::nested_string_case::rule::META,
        &paredit_feature_lint_string_char::nested_string_case::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::code_char_char_code::rule::META,
        &paredit_feature_lint_string_char::code_char_char_code::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::last_default_count::rule::META,
        &paredit_feature_lint_sequence::last_default_count::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::butlast_default_count::rule::META,
        &paredit_feature_lint_form_shape::butlast_default_count::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_list_default_element::rule::META,
        &paredit_feature_lint_form_shape::make_list_default_element::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::parse_integer_default_radix::rule::META,
        &paredit_feature_lint_form_shape::parse_integer_default_radix::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::getf_default_nil::rule::META,
        &paredit_feature_lint_form_shape::getf_default_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_array_default_keyword::rule::META,
        &paredit_feature_lint_form_shape::make_array_default_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::nested_char_case::rule::META,
        &paredit_feature_lint_form_shape::nested_char_case::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::list_star_nil::rule::META,
        &paredit_feature_lint_sequence::list_star_nil::rule::RULE,
    ),
];
