//! Application use cases for Lisp-aware analysis, reporting, and refactor planning.
//!
//! These services orchestrate typed domain operations into agent-facing plans,
//! reports, and workspace workflows without coupling to the CLI shell.

pub mod butlast_default_count_report;
pub mod case_nil_key_report;
pub mod coerce_to_t_report;
pub mod cond_t_clause_report;
pub(crate) mod conditional_sugar;
pub mod constant_if_test_report;
pub mod constant_when_test_report;
pub mod convert_cond_to_if;
pub mod convert_if_to_cond;
pub mod convert_if_to_unless;
pub mod convert_if_to_when;
pub mod convert_unless_to_if;
pub mod convert_when_to_if;
pub mod de_morgan_report;
pub mod dead_boolean_operand_report;
pub mod defpackage_quoted_report;
pub mod duplicate_boolean_operand_report;
pub mod duplicate_case_key_report;
pub mod duplicate_cond_test_report;
pub mod duplicate_export_report;
pub mod duplicate_keyword_report;
pub mod duplicate_lambda_list_keyword_report;
pub mod duplicate_let_binding_report;
pub mod duplicate_method_report;
pub mod duplicate_parameter_report;
pub mod duplicate_setf_place_report;
pub mod duplicate_slot_report;
pub mod empty_body_report;
pub mod empty_let_report;
pub mod exhaustive_case_otherwise_report;
pub mod funcall_lambda_report;
pub mod getf_default_nil_report;
pub mod gethash_default_report;
pub mod identical_if_branch_report;
pub mod if_arity_report;
pub mod if_not_report;
pub mod if_to_or_report;
pub mod if_to_unless_report;
pub mod inline_literal_constant;
pub mod lambda_list_keyword_order_report;
pub mod lint_report;
pub mod make_array_default_keyword_report;
pub mod make_hash_table_test_report;
pub mod make_list_default_element_report;
pub mod malformed_case_clause_report;
pub mod malformed_cond_clause_report;
pub mod malformed_let_binding_report;
pub mod manual_incf_report;
pub mod manual_push_report;
pub mod manual_pushnew_report;
pub mod multiple_value_list_of_values_report;
pub(crate) mod mutation_safety;
pub mod negated_comparison_report;
pub mod negated_if_report;
pub mod negated_when_unless_report;
pub mod nested_boolean_report;
pub mod nested_char_case_report;
pub mod nested_cxr_report;
pub mod nested_unless_report;
pub mod nested_when_report;
pub mod one_armed_if_report;
pub mod parse_integer_default_radix_report;
pub mod quoted_case_key_report;
pub mod redundant_apply_report;
pub mod redundant_boolean_identity_report;
pub mod redundant_funcall_report;
pub mod redundant_identity_report;
pub mod redundant_if_nil_report;
pub mod redundant_let_star_report;
pub mod redundant_quote_report;
pub mod redundant_the_report;
pub mod self_assignment_report;
pub mod semantic_coverage;
pub mod setf_arity_report;
pub mod setq_non_variable_report;
pub mod shadowed_binding_report;
pub mod sharp_quoted_lambda_report;
pub mod single_clause_cond_report;
pub mod single_operand_boolean_report;
pub mod single_value_bind_report;
pub mod the_arity_report;
pub mod typecase_nil_key_report;
pub mod typep_predicate_report;
pub mod unreachable_case_clause_report;
pub mod unreachable_cond_clause_report;
pub mod unused_parameter_report;
pub mod values_list_of_list_report;

// Phase 3 facade (section 4.1). benches/similarity_report.rs uses
// `paredit_cli::application::usecase::similarity_report`, so this path stays.
pub use paredit_feature_similarity::duplicate_report::usecase as duplicate_report;
pub use paredit_feature_similarity::similarity_report::usecase as similarity_report;

pub use paredit_feature_extract::extract_constant::usecase as extract_constant;
pub use paredit_feature_extract::extract_function::usecase as extract_function;
pub use paredit_feature_extract::extract_local_function::usecase as extract_local_function;

pub use paredit_feature_inline::inline_function::usecase as inline_function;
pub use paredit_feature_inline::inline_lambda::usecase as inline_lambda;
pub use paredit_feature_inline::inline_let::usecase as inline_let;
pub use paredit_feature_inline::inline_local_function::usecase as inline_local_function;
pub use paredit_feature_inline::inline_symbol_macro::usecase as inline_symbol_macro;

pub use paredit_feature_form_transform::replace_forms::usecase as replace_forms;
pub use paredit_feature_form_transform::sort_definitions::usecase as sort_definitions;
pub use paredit_feature_form_transform::split_file::usecase as split_file;
pub use paredit_feature_form_transform::thread_expression::usecase as thread_expression;
pub use paredit_feature_form_transform::unthread_expression::usecase as unthread_expression;
pub use paredit_feature_form_transform::unwrap_call::usecase as unwrap_call;

// Facade re-exports for extracted feature packages (section 4.1).
pub use paredit_feature_binding::convert_flet_to_labels::usecase as convert_flet_to_labels;
pub use paredit_feature_binding::convert_labels_to_flet::usecase as convert_labels_to_flet;
pub use paredit_feature_binding::convert_let_star_to_let::usecase as convert_let_star_to_let;
pub use paredit_feature_binding::convert_let_to_let_star::usecase as convert_let_to_let_star;
pub use paredit_feature_binding::convert_sequential_binding::usecase as convert_sequential_binding;
pub use paredit_feature_binding::eliminate_empty_binding_form::usecase as eliminate_empty_binding_form;
pub use paredit_feature_binding::flatten_progn::usecase as flatten_progn;
pub use paredit_feature_binding::introduce_let::usecase as introduce_let;
pub use paredit_feature_binding::let_report::usecase as let_report;
pub use paredit_feature_binding::merge_nested_flet::usecase as merge_nested_flet;
pub use paredit_feature_binding::merge_nested_let::usecase as merge_nested_let;
pub use paredit_feature_binding::merge_nested_let_star::usecase as merge_nested_let_star;
pub use paredit_feature_binding::split_let::usecase as split_let;
pub use paredit_feature_binding::split_let_star::usecase as split_let_star;
pub use paredit_feature_function_parameter::function_parameter::usecase as function_parameter;
pub use paredit_feature_lint_control_flow::binds_constant::usecase as binds_constant_report;
pub use paredit_feature_lint_control_flow::eval_when_situation::usecase as eval_when_situation_report;
pub use paredit_feature_lint_control_flow::explicit_nil_return::usecase as explicit_nil_return_report;
pub use paredit_feature_lint_control_flow::handler_case_no_clauses::usecase as handler_case_no_clauses_report;
pub use paredit_feature_lint_control_flow::malformed_iteration_spec::usecase as malformed_iteration_spec_report;
pub use paredit_feature_lint_control_flow::nested_progn::usecase as nested_progn_report;
pub use paredit_feature_lint_control_flow::prog2_to_progn::usecase as prog2_to_progn_report;
pub use paredit_feature_lint_control_flow::redundant_body_progn::usecase as redundant_body_progn_report;
pub use paredit_feature_lint_control_flow::redundant_prog1::usecase as redundant_prog1_report;
pub use paredit_feature_lint_control_flow::redundant_progn::usecase as redundant_progn_report;
pub use paredit_feature_lint_control_flow::unwind_protect_no_cleanup::usecase as unwind_protect_no_cleanup_report;
pub use paredit_feature_lint_numeric::eq_char_comparison::usecase as eq_char_comparison_report;
pub use paredit_feature_lint_numeric::eq_number_comparison::usecase as eq_number_comparison_report;
pub use paredit_feature_lint_numeric::eql_list_comparison::usecase as eql_list_comparison_report;
pub use paredit_feature_lint_numeric::eql_string_comparison::usecase as eql_string_comparison_report;
pub use paredit_feature_lint_numeric::equality_arity::usecase as equality_arity_report;
pub use paredit_feature_lint_numeric::explicit_step_delta::usecase as explicit_step_delta_report;
pub use paredit_feature_lint_numeric::identity_arithmetic::usecase as identity_arithmetic_report;
pub use paredit_feature_lint_numeric::literal_place::usecase as literal_place_report;
pub use paredit_feature_lint_numeric::modify_macro_arity::usecase as modify_macro_arity_report;
pub use paredit_feature_lint_numeric::negated_step_delta::usecase as negated_step_delta_report;
pub use paredit_feature_lint_numeric::nil_comparison::usecase as nil_comparison_report;
pub use paredit_feature_lint_numeric::one_step_arithmetic::usecase as one_step_arithmetic_report;
pub use paredit_feature_lint_numeric::redundant_divisor::usecase as redundant_divisor_report;
pub use paredit_feature_lint_numeric::self_comparison::usecase as self_comparison_report;
pub use paredit_feature_lint_numeric::sign_comparison::usecase as sign_comparison_report;
pub use paredit_feature_lint_numeric::single_arg_comparison::usecase as single_arg_comparison_report;
pub use paredit_feature_lint_numeric::single_operand_arithmetic::usecase as single_operand_arithmetic_report;
pub use paredit_feature_lint_numeric::step_zero::usecase as step_zero_report;
pub use paredit_feature_lint_numeric::t_comparison::usecase as t_comparison_report;
pub use paredit_feature_lint_numeric::verbose_negation::usecase as verbose_negation_report;
pub use paredit_feature_lint_numeric::zero_divisor::usecase as zero_divisor_report;
pub use paredit_feature_lint_sequence::accessor_arity::usecase as accessor_arity_report;
pub use paredit_feature_lint_sequence::append_list_to_cons::usecase as append_list_to_cons_report;
pub use paredit_feature_lint_sequence::append_nil::usecase as append_nil_report;
pub use paredit_feature_lint_sequence::car_nthcdr::usecase as car_nthcdr_report;
pub use paredit_feature_lint_sequence::car_reverse::usecase as car_reverse_report;
pub use paredit_feature_lint_sequence::cons_to_list::usecase as cons_to_list_report;
pub use paredit_feature_lint_sequence::destructive_literal::usecase as destructive_literal_report;
pub use paredit_feature_lint_sequence::double_reverse::usecase as double_reverse_report;
pub use paredit_feature_lint_sequence::eql_search_literal::usecase as eql_search_literal_report;
pub use paredit_feature_lint_sequence::last_default_count::usecase as last_default_count_report;
pub use paredit_feature_lint_sequence::list_star_nil::usecase as list_star_nil_report;
pub use paredit_feature_lint_sequence::list_star_to_cons::usecase as list_star_to_cons_report;
pub use paredit_feature_lint_sequence::nth_constant_index::usecase as nth_constant_index_report;
pub use paredit_feature_lint_sequence::nthcdr_small_index::usecase as nthcdr_small_index_report;
pub use paredit_feature_lint_sequence::nthcdr_zero::usecase as nthcdr_zero_report;
pub use paredit_feature_lint_sequence::redundant_count_nil::usecase as redundant_count_nil_report;
pub use paredit_feature_lint_sequence::redundant_end_nil::usecase as redundant_end_nil_report;
pub use paredit_feature_lint_sequence::redundant_eql_test::usecase as redundant_eql_test_report;
pub use paredit_feature_lint_sequence::redundant_from_end_nil::usecase as redundant_from_end_nil_report;
pub use paredit_feature_lint_sequence::redundant_identity_key::usecase as redundant_identity_key_report;
pub use paredit_feature_lint_sequence::redundant_start_zero::usecase as redundant_start_zero_report;
pub use paredit_feature_lint_sequence::single_operand_list_op::usecase as single_operand_list_op_report;
pub use paredit_feature_lint_sequence::subseq_zero::usecase as subseq_zero_report;
pub use paredit_feature_lint_string_char::char_case_fold::usecase as char_case_fold_report;
pub use paredit_feature_lint_string_char::char_op_string::usecase as char_op_string_report;
pub use paredit_feature_lint_string_char::code_char_char_code::usecase as code_char_char_code_report;
pub use paredit_feature_lint_string_char::format_missing_destination::usecase as format_missing_destination_report;
pub use paredit_feature_lint_string_char::format_newline::usecase as format_newline_report;
pub use paredit_feature_lint_string_char::format_to_string::usecase as format_to_string_report;
pub use paredit_feature_lint_string_char::nested_string_case::usecase as nested_string_case_report;
pub use paredit_feature_lint_string_char::string_case_fold::usecase as string_case_fold_report;
pub use paredit_feature_package::dependency_report::usecase as dependency_report;
pub use paredit_feature_package::package::usecase as package;
pub use paredit_feature_package::package_boundary_report::usecase as package_boundary_report;
pub use paredit_feature_package::package_conflict_report::usecase as package_conflict_report;
pub use paredit_feature_package::package_report::usecase as package_report;
pub use paredit_feature_package::system_conflict_report::usecase as system_conflict_report;
pub use paredit_feature_package::unused_export_report::usecase as unused_export_report;
pub use paredit_feature_package::unused_nickname_report::usecase as unused_nickname_report;
pub use paredit_feature_package::unused_package_report::usecase as unused_package_report;
pub use paredit_feature_project_analysis::call_cycle_report::usecase as call_cycle_report;
pub use paredit_feature_project_analysis::call_graph_report::usecase as call_graph_report;
pub use paredit_feature_project_analysis::call_report::usecase as call_report;
pub use paredit_feature_project_analysis::class_cycle_report::usecase as class_cycle_report;
pub use paredit_feature_project_analysis::complexity_report::usecase as complexity_report;
pub use paredit_feature_project_analysis::form_report::usecase as form_report;
pub use paredit_feature_project_analysis::impact_report::usecase as impact_report;
pub use paredit_feature_project_analysis::naming_report::usecase as naming_report;
pub use paredit_feature_project_analysis::package_cycle_report::usecase as package_cycle_report;
pub use paredit_feature_project_analysis::reachability_report::usecase as reachability_report;
pub use paredit_feature_project_analysis::redefinition_report::usecase as redefinition_report;
pub use paredit_feature_project_analysis::signature_report::usecase as signature_report;
pub use paredit_feature_project_analysis::struct_cycle_report::usecase as struct_cycle_report;
pub use paredit_feature_project_analysis::system_cycle_report::usecase as system_cycle_report;
pub use paredit_feature_project_analysis::undefined_package_report::usecase as undefined_package_report;
pub use paredit_feature_project_analysis::unused_local_callable_report::usecase as unused_local_callable_report;
pub use paredit_feature_project_analysis::workspace_report::usecase as workspace_report;
pub use paredit_feature_refactor_workflow::refactor::usecase as refactor;
pub use paredit_feature_remove_unused::definition_report::usecase as definition_report;
pub use paredit_feature_remove_unused::remove_definition::usecase as remove_definition;
pub use paredit_feature_remove_unused::remove_unused_binding::usecase as remove_unused_binding;
pub use paredit_feature_remove_unused::remove_unused_control::usecase as remove_unused_control;
pub use paredit_feature_remove_unused::remove_unused_definition::usecase as remove_unused_definition;
pub use paredit_feature_rename::rename::usecase as rename;
pub use paredit_feature_rename::rename_control::usecase as rename_control;
