/// An Emacs Lisp operator whose shape this tool models.
///
/// The list is deliberately concrete rather than pattern-based. `defun` and
/// `cl-defun` differ in their lambda lists, `let` and `dlet` differ in what
/// they bind, and `if-let*` puts its body somewhere `let*` does not — a
/// prefix rule over `def`/`cl-` would flatten all three distinctions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum EmacsLispOperator {
    // Lexical binding forms.
    Let,
    LetStar,
    Letrec,
    Dlet,
    NamedLet,
    ClLetf,
    ClLetfStar,
    ClSymbolMacrolet,
    // Conditional binding forms from `subr-x` / `cl-lib`.
    IfLet,
    IfLetStar,
    WhenLet,
    WhenLetStar,
    AndLetStar,
    WhileLet,
    // Destructuring binding forms.
    ClDestructuringBind,
    ClMultipleValueBind,
    PcaseLet,
    PcaseLetStar,
    SeqLet,
    // Iteration binding forms.
    Dolist,
    Dotimes,
    ClDolist,
    ClDotimes,
    PcaseDolist,
    ClDo,
    ClDoStar,
    ClLoop,
    // Local callables.
    ClFlet,
    ClFletStar,
    ClLabels,
    ClMacrolet,
    // Obsolete `cl.el` spellings still found in the wild.
    Flet,
    Labels,
    // Condition and non-local exit forms that bind.
    ConditionCase,
    ConditionCaseUnlessDebug,
    // EIEIO slot access.
    WithSlots,
    // Anonymous callables.
    Lambda,
    Closure,
    ClFunction,
    // Function definitions.
    Defun,
    Defsubst,
    Defmacro,
    DefineInline,
    ClDefun,
    ClDefsubst,
    ClDefmacro,
    ClDefgeneric,
    ClDefmethod,
    ClDefineCompilerMacro,
    Defadvice,
    DefineAdvice,
    Defalias,
    DefineObsoleteFunctionAlias,
    DeclareFunction,
    ErtDeftest,
    // Type definitions.
    ClDefstruct,
    ClDeftype,
    DefineError,
    Defclass,
    // Variable definitions.
    Defvar,
    DefvarLocal,
    DefvarKeymap,
    Defconst,
    Defvaralias,
    DefineObsoleteVariableAlias,
    // Customization definitions.
    Defcustom,
    Defface,
    Defgroup,
    Deftheme,
    DefineWidget,
    // Mode definitions.
    DefineMinorMode,
    DefineDerivedMode,
    DefineGlobalizedMinorMode,
    DefineGlobalMinorMode,
    DefineGenericMode,
    DefineCompilationMode,
    // Load-time dependency forms.
    Require,
    Provide,
    Load,
    LoadFile,
    LoadLibrary,
    Autoload,
    DefinePackage,
    // Compile-time wrappers.
    EvalWhenCompile,
    EvalAndCompile,
    WithNoWarnings,
    WithSuppressedWarnings,
    // Sequencing and control forms this layer evaluates in place.
    Progn,
    Prog1,
    Prog2,
    ClBlock,
    ClReturnFrom,
    Catch,
    UnwindProtect,
    SaveExcursion,
    SaveRestriction,
    SaveMatchData,
    SaveCurrentBuffer,
    SaveWindowExcursion,
    WithCurrentBuffer,
    WithTempBuffer,
    WithTempFile,
    WithOutputToString,
    WithOutputToTempBuffer,
    WithSilentModifications,
    WithSelectedWindow,
    WithSyntaxTable,
    Declare,
    ClDeclare,
    Interactive,
    Pcase,
    PcaseExhaustive,
    ClCase,
    ClEcase,
    ClTypecase,
    ClEtypecase,
}
