//! The JSON Schema for the `inspect capabilities` document.
//!
//! The catalog is this tool's machine-readable interface: an agent reads it to
//! learn every command, flag, default, and enum value without a failed
//! invocation per discovery. Publishing a schema for it is what turns that from
//! "a JSON blob you can pattern-match" into something a consumer can generate
//! types from and validate against.
//!
//! Written by hand rather than derived. The catalog is not a Rust type — it is
//! assembled from clap's own command tree — so there is nothing to derive from,
//! and a hand-written schema is anyway the only one that can carry the
//! *meaning* of a field: that `possible_values` absent means the option is not
//! an enum, that `silent` means a command ran and knew nothing.
//!
//! The version parameter matters: schema version 1 has no `dialect_contract`,
//! 2 adds it without tiers, 3 adds tiers and the `silent` status. A single
//! permissive schema covering all three would validate a version 1 document
//! carrying a version 3 field, which is exactly the drift the catalog's
//! version number exists to catch.
//!
//! `command.writes` and `command.possible_error_codes` are the one
//! deliberate exception to that discipline: both are populated on every
//! command regardless of `schema_version`, and their `$defs` entry (in
//! [`definitions`]) is not gated behind a `version >= N` check the way
//! `dialectContract` is. That is safe rather than an oversight, because the
//! two things a version number has to protect against don't apply to them:
//! they are additive-only leaf properties on a node that already exists in
//! every version (unlike `dialect_contract`, which changes the *shape* of
//! the document by adding a whole new top-level collection), and no version
//! ever populated the catalog without them, so there is no older document
//! shape a schema revision could be asked to keep validating. Widening a
//! schema in place is exactly the drift this module otherwise refuses to
//! allow — the fields are exempted here, not the discipline.
//! `cli_capabilities_schema_pins_writes_and_error_codes_as_intentionally_unversioned`
//! in `tests/cli/capabilities_schema.rs` pins this as a tested contract
//! rather than a comment that can go stale.

use serde_json::{Value, json};

/// The published schema identifier, versioned alongside the catalog.
fn schema_id(version: u8) -> String {
    format!("https://nerima-lisp.github.io/paredit-cli/schema/capabilities-v{version}.json")
}

/// Builds the JSON Schema (draft 2020-12) for a capabilities document at
/// `version`.
pub(super) fn capabilities_schema(version: u8) -> Value {
    let mut root = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": schema_id(version),
        "title": format!("paredit inspect capabilities, schema version {version}"),
        "description":
            "The machine-readable catalog of every paredit command, flag, default, and \
             enum value, generated by walking the argument parser's own command tree.",
        "type": "object",
        "required": ["schema_version", "name", "commands"],
        "additionalProperties": false,
        "properties": {
            "schema_version": {
                "const": version,
                "description":
                    "The catalog's own version. A consumer should validate against the \
                     schema matching this number rather than the newest one.",
            },
            "name": { "type": "string", "const": "paredit" },
            "version": {
                "type": ["string", "null"],
                "description": "The paredit release that produced this catalog.",
            },
            "about": { "type": ["string", "null"] },
            "commands": {
                "type": "array",
                "items": { "$ref": "#/$defs/command" },
            },
        },
        "$defs": definitions(version),
    });

    if version >= 2 {
        root["required"]
            .as_array_mut()
            .expect("required array")
            .push(json!("dialect_contract"));
        root["properties"]["dialect_contract"] = json!({ "$ref": "#/$defs/dialectContract" });
    }

    root
}

fn definitions(version: u8) -> Value {
    let mut defs = json!({
        "command": {
            "type": "object",
            "description":
                "One command or namespace. A node carrying `commands` is a namespace \
                 (`inspect`, `edit`, `refactor`); a leaf without it is invocable.",
            "required": ["name", "args"],
            "additionalProperties": false,
            "properties": {
                "name": { "type": "string" },
                "about": { "type": ["string", "null"] },
                "args": { "type": "array", "items": { "$ref": "#/$defs/argument" } },
                "commands": { "type": "array", "items": { "$ref": "#/$defs/command" } },
                "gates": {
                    "type": "array",
                    "description":
                        "The policy gates this command offers. Absent, not empty, on a \
                         command that has none, so \"cannot fail on a policy\" and \"we \
                         did not look\" stay distinguishable.",
                    "items": { "$ref": "#/$defs/gate" },
                },
                "writes": {
                    "type": "boolean",
                    "description":
                        "Whether this command is capable of modifying a file under some \
                         argument combination — a `--write`/`--fix`/`--apply`/`--in-place` \
                         flag, or a command whose name is itself the write (`fix apply`). \
                         Present only on an invocable command, absent on a namespace node \
                         that only groups other commands. `false` on a command that can \
                         still touch disk outside this promise — the kill ring \
                         (`--to-ring`) and archive extraction (`--extract-to`) are not \
                         counted, matching the `--read-only` MCP gate this mirrors.",
                },
                "possible_error_codes": {
                    "type": "array",
                    "description":
                        "The `ErrorCode` labels (see `docs/src/reference/errors.md`) this \
                         command can realistically exit with, such as \
                         `input.dialect-unsupported` or `selection.no-match`. A superset \
                         gathered from the command's own argument shape rather than a \
                         proof of completeness: absence of a code here means no known \
                         signal predicts it, not that it is provably unreachable. Present \
                         only on an invocable command, same as `writes`.",
                    "items": { "type": "string" },
                },
            },
        },
        "gate": {
            "type": "object",
            "description":
                "One flag that makes the command exit non-zero after its report is \
                 printed. The spelling determines the kind.",
            "required": ["flag", "kind", "exit_code"],
            "additionalProperties": false,
            "properties": {
                "flag": {
                    "type": "string",
                    "description": "The long flag, with its leading dashes.",
                },
                "kind": {
                    "enum": ["severity", "presence", "minimum"],
                    "description":
                        "`severity` fails on a finding at or above a level \
                         (`--fail-on <severity>`); `presence` fails when any of the \
                         named thing was found (`--fail-on-<thing>`); `minimum` fails \
                         when fewer than N were (`--require-<thing> <N>`).",
                },
                "help": { "type": ["string", "null"] },
                "exit_code": {
                    "type": "integer",
                    "description": "The process exit status this gate produces.",
                },
            },
        },
        "argument": {
            "type": "object",
            "required": ["id", "kind", "required", "repeatable"],
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string",
                    "description":
                        "The argument's internal identifier. Stable across releases \
                         even when the spelling of `long` changes.",
                },
                "long": {
                    "type": ["string", "null"],
                    "description": "The `--flag` spelling, without the dashes.",
                },
                "short": { "type": ["string", "null"] },
                "kind": {
                    "enum": ["positional", "option", "flag"],
                    "description":
                        "`flag` takes no value; `option` takes one; `positional` is \
                         supplied without a name.",
                },
                "help": { "type": ["string", "null"] },
                "required": { "type": "boolean" },
                "repeatable": {
                    "type": "boolean",
                    "description": "Whether passing the argument more than once accumulates.",
                },
                "value_names": { "type": ["array", "null"], "items": { "type": "string" } },
                "default_values": { "type": "array", "items": { "type": "string" } },
                "possible_values": {
                    "type": ["array", "null"],
                    "items": { "type": "string" },
                    "description":
                        "The accepted values when the argument is an enum. Null — not \
                         an empty array — when it accepts free text.",
                },
            },
        },
    });

    if version >= 2 {
        defs["dialectContract"] = dialect_contract_schema(version);
        defs["commandSupport"] = command_support_schema(version);
    }

    defs
}

/// The status vocabulary a schema version can express.
///
/// `silent` — the command ran, exited zero, and knew nothing about the file's
/// dialect — is the distinction version 3 added. Earlier versions fold it onto
/// `unsupported`, so their schemas must not admit the word.
fn status_values(version: u8) -> Value {
    if version >= 3 {
        json!(["supported", "silent", "unsupported", "unknown"])
    } else {
        json!(["supported", "unsupported", "unknown"])
    }
}

fn dialect_contract_schema(version: u8) -> Value {
    let statuses = status_values(version);

    let mut schema = json!({
        "type": "object",
        "description":
            "How far each command's analysis reaches into each dialect. This tool \
             parses ten dialects and models far fewer of them semantically; the \
             contract is what separates 'found nothing' from 'looked for nothing'.",
        "required": [
            "command_count", "dialect_count", "cell_count",
            "categories", "statuses", "dialects", "commands",
        ],
        "additionalProperties": false,
        "properties": {
            "command_count": { "type": "integer", "minimum": 0 },
            "dialect_count": { "type": "integer", "minimum": 0 },
            "cell_count": {
                "type": "integer",
                "minimum": 0,
                "description": "command_count × dialect_count, the size of the matrix.",
            },
            "categories": {
                "type": "array",
                "items": { "enum": ["introspection", "format", "structural", "semantic"] },
            },
            "statuses": { "type": "array", "items": { "enum": statuses } },
            "dialects": { "type": "array", "items": { "type": "string" } },
            "commands": { "type": "array", "items": { "$ref": "#/$defs/commandSupport" } },
        },
    });

    if version >= 3 {
        for key in ["tiers", "semantic_layers", "dialect_depth"] {
            schema["required"]
                .as_array_mut()
                .expect("required array")
                .push(json!(key));
        }
        schema["properties"]["tiers"] = json!({
            "type": "array",
            "items": { "enum": ["syntax", "scope", "common-lisp-family", "common-lisp-semantics"] },
            "description":
                "What a command needs from a dialect before its analysis means \
                 anything, from the balanced-parens tree up to the Common Lisp \
                 package and operator model.",
        });
        schema["properties"]["semantic_layers"] = json!({
            "type": "array",
            "items": { "enum": semantic_layer_values() },
            "description":
                "The semantic layers the `common-lisp-semantics` tier's six \
                 introspection commands (types, narrowing, constants, \
                 value-propagation, effects, semantic-coverage) are actually \
                 built from. Each names the field a command with that layer \
                 carries in `commands[].layer`.",
        });
        schema["properties"]["dialect_depth"] = json!({
            "type": "array",
            "description":
                "Per dialect, how many commands land in each status — the answer to \
                 'how deep does this tool go for my dialect' in one read.",
            "items": {
                "type": "object",
                "required": [
                    "dialect", "family", "separates_function_namespace",
                    "by_status", "verified_semantic_operations",
                ],
                "additionalProperties": false,
                "properties": {
                    "dialect": { "type": "string" },
                    "family": {
                        "type": "string",
                        "description": "The dialect's own name for itself, spelled as its \
                                        community spells it.",
                    },
                    "separates_function_namespace": {
                        "type": "boolean",
                        "description":
                            "Whether the dialect is a Lisp-2. It decides whether a rename \
                             of a variable can collide with a function of the same name.",
                    },
                    "by_status": {
                        "type": "object",
                        "description": "How many commands land in each status for this dialect.",
                        "additionalProperties": { "type": "integer", "minimum": 0 },
                    },
                    "verified_semantic_operations": {
                        "type": "array",
                        "items": { "type": "string" },
                        "description":
                            "The scope-level operations this dialect is tested against, \
                             as opposed to merely parsed for.",
                    },
                },
            },
        });
    }

    schema
}

fn command_support_schema(version: u8) -> Value {
    let statuses = status_values(version);
    let mut schema = json!({
        "type": "object",
        "required": ["path", "category", "support"],
        "additionalProperties": false,
        "properties": {
            "path": {
                "type": "string",
                "description": "The command's space-separated path, e.g. `inspect lint`.",
            },
            "category": {
                "enum": ["introspection", "format", "structural", "semantic"],
            },
            "support": {
                "type": "object",
                "description": "One status per dialect, keyed by the dialect's name.",
                "additionalProperties": { "enum": statuses },
            },
        },
    });

    if version >= 3 {
        schema["required"]
            .as_array_mut()
            .expect("required array")
            .push(json!("tier"));
        schema["properties"]["tier"] = json!({
            "enum": ["syntax", "scope", "common-lisp-family", "common-lisp-semantics"],
        });
        // Optional, not required: only the six `common-lisp-semantics`-tier
        // introspection commands (types, narrowing, constants,
        // value-propagation, effects, semantic-coverage) carry a layer. Every
        // other command's dialect support is fully named by its tier alone.
        schema["properties"]["layer"] = json!({
            "enum": semantic_layer_values(),
            "description":
                "Which semantic layer actually decided this command's dialect \
                 support, for the commands whose tier is \
                 `common-lisp-semantics`. Absent for every other command.",
        });
    }

    schema
}

fn semantic_layer_values() -> Value {
    json!([
        "typing",
        "narrowing",
        "constants",
        "value-propagation",
        "effects",
        "semantic-coverage",
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_schema_pins_the_version_it_describes() {
        for version in 1..=3 {
            let schema = capabilities_schema(version);
            assert_eq!(schema["properties"]["schema_version"]["const"], version);
            assert!(
                schema["$id"]
                    .as_str()
                    .is_some_and(|id| id.ends_with(&format!("capabilities-v{version}.json"))),
                "version {version} must publish under its own id"
            );
        }
    }

    /// Version 1 has no dialect contract, so its schema must not admit one.
    ///
    /// A single permissive schema would validate a version 1 document carrying
    /// a version 3 field, which is the drift the version number exists to
    /// catch.
    #[test]
    fn version_one_rejects_the_dialect_contract_it_does_not_carry() {
        let schema = capabilities_schema(1);
        assert_eq!(schema["additionalProperties"], false);
        assert!(schema["properties"]["dialect_contract"].is_null());
        assert!(schema["$defs"]["dialectContract"].is_null());
    }

    #[test]
    fn the_silent_status_and_tiers_appear_only_from_version_three() {
        let statuses = |version| {
            capabilities_schema(version)["$defs"]["dialectContract"]["properties"]["statuses"]
                ["items"]["enum"]
                .clone()
        };
        assert_eq!(statuses(2), json!(["supported", "unsupported", "unknown"]));
        assert_eq!(
            statuses(3),
            json!(["supported", "silent", "unsupported", "unknown"])
        );
        assert!(
            capabilities_schema(2)["$defs"]["dialectContract"]["properties"]["tiers"].is_null()
        );
    }
}
