//! `cargo xtask new-lint-rule` — scaffolds one rule inside an existing
//! `lint-<theme>` package (`domain`/`usecase`/`rule` plus the four-file
//! `cli` module, in the shape every rule in the suite already uses) and
//! performs the two registrations that are safe to automate because they
//! are pure arithmetic over a single well-known pattern:
//!
//! - `RULE_COUNT` and the `REGISTRY` array in
//!   `src/lint/registry/mod.rs`
//! - the matching `fixable_count()`/`warning_count()` assertions in
//!   `src/lint/registry/catalog.rs`, derived from the `Fixability`/
//!   `Severity` this rule's own generated `META` declares
//!
//! Everything past that — the standalone `inspect <rule>` command's six-file
//! wiring, and the rule-count prose scattered across docs/ — is printed as a
//! checklist by `crate::checklist`, not edited, for the reason explained
//! there.

use std::fs;

use crate::error::Result;

use crate::case::Name;
use crate::checklist::{self, Namespace};
use crate::fs_util::{insert_sorted_mod_line, write_new_file};
use crate::repo::Repo;

pub struct NewLintRuleOptions {
    pub theme: String,
    pub name: Name,
    pub description: String,
}

pub fn run(repo: &Repo, options: &NewLintRuleOptions) -> Result<()> {
    let package = format!("lint-{}", options.theme);
    let package_dir = repo.feature_package(&package)?;
    let crate_name = format!("paredit_feature_lint_{}", options.theme.replace('-', "_"));
    let snake = options.name.snake();
    let pascal = options.name.pascal();
    let kebab = options.name.kebab();
    let description = &options.description;
    let rule_dir = package_dir.join("src").join(&snake);

    if rule_dir.exists() {
        return Err(crate::error::XtaskError::refused(format!(
            "{} already exists",
            rule_dir.display()
        )));
    }

    write_new_file(
        &rule_dir.join("mod.rs"),
        &format!(
            "//! The `{kebab}` lint rule: its adapter, detection, use case and command.\n\
             //!\n\
             //! One rule, one directory. `rule` is what the registry registers; the other\n\
             //! three are the report it drives.\n\n\
             pub mod cli;\n\
             pub mod domain;\n\
             pub mod rule;\n\
             pub mod usecase;\n"
        ),
    )?;

    write_new_file(
        &rule_dir.join("domain.rs"),
        &format!(
            "//! `{kebab}` detection: TODO — {description}.\n\
             //!\n\
             //! Generated by `cargo xtask new-lint-rule`. Replace `examine`'s body with the\n\
             //! real detection, then update the item/summary fields it needs to report.\n\n\
             use std::path::{{Path, PathBuf}};\n\n\
             use paredit_core_lint_engine::LintResult;\n\n\
             use paredit_core_syntax::dialect::Dialect;\n\
             use paredit_core_syntax::sexpr::{{ByteSpan, ExpressionView, Path as SexprPath, SyntaxTree}};\n\
             use paredit_core_syntax::view_query::for_each_subview;\n\n\
             #[derive(Debug, Clone)]\n\
             pub struct {pascal}Item {{\n\
             \x20   pub path: PathBuf,\n\
             \x20   pub span: ByteSpan,\n\
             }}\n\n\
             #[derive(Debug)]\n\
             pub struct {pascal}Summary {{\n\
             \x20   pub scanned_form_count: usize,\n\
             \x20   pub violations: Vec<{pascal}Item>,\n\
             }}\n\n\
             #[derive(Debug, Clone, Copy)]\n\
             pub struct {pascal}PolicyOptions {{\n\
             \x20   fail_on_violation: bool,\n\
             }}\n\n\
             impl {pascal}PolicyOptions {{\n\
             \x20   #[must_use]\n\
             \x20   pub const fn new(fail_on_violation: bool) -> Self {{\n\
             \x20       Self {{ fail_on_violation }}\n\
             \x20   }}\n\n\
             \x20   #[must_use]\n\
             \x20   pub const fn fail_on_violation(self) -> bool {{\n\
             \x20       self.fail_on_violation\n\
             \x20   }}\n\
             }}\n\n\
             #[derive(Debug)]\n\
             pub struct {pascal}Policy {{\n\
             \x20   pub fail_on_violation: bool,\n\
             \x20   pub scanned_form_count: usize,\n\
             \x20   pub violation_count: usize,\n\
             \x20   pub passed: bool,\n\
             \x20   pub violations: Vec<String>,\n\
             }}\n\n\
             /// Examines one node. Shared with the lint suite's rule, which reaches every\n\
             /// node through the single dispatch pass instead of walking the tree again.\n\
             ///\n\
             /// TODO: replace this stub with the real detection for {description}.\n\
             pub fn examine(\n\
             \x20   _view: &ExpressionView,\n\
             \x20   _path: &Path,\n\
             \x20   _scanned_form_count: &mut usize,\n\
             \x20   _violations: &mut Vec<{pascal}Item>,\n\
             ) {{\n\
             }}\n\n\
             /// Collects every violation across a whole file, along with the total number of\n\
             /// forms scanned.\n\
             pub fn collect_{snake}(\n\
             \x20   path: &Path,\n\
             \x20   _dialect: Dialect,\n\
             \x20   tree: &SyntaxTree,\n\
             ) -> LintResult<(usize, Vec<{pascal}Item>)> {{\n\
             \x20   let mut scanned_form_count = 0;\n\
             \x20   let mut violations = Vec::new();\n\
             \x20   for index in 0..tree.root_children().len() {{\n\
             \x20       let view = tree.select_path(&SexprPath::root_child(index))?.view();\n\
             \x20       for_each_subview(&view, |subview| {{\n\
             \x20           examine(subview, path, &mut scanned_form_count, &mut violations);\n\
             \x20       }});\n\
             \x20   }}\n\
             \x20   Ok((scanned_form_count, violations))\n\
             }}\n\n\
             #[must_use]\n\
             pub const fn summarize_{snake}(\n\
             \x20   scanned_form_count: usize,\n\
             \x20   violations: Vec<{pascal}Item>,\n\
             ) -> {pascal}Summary {{\n\
             \x20   {pascal}Summary {{\n\
             \x20       scanned_form_count,\n\
             \x20       violations,\n\
             \x20   }}\n\
             }}\n\n\
             #[must_use]\n\
             pub fn evaluate_{snake}_policy(\n\
             \x20   options: {pascal}PolicyOptions,\n\
             \x20   summary: &{pascal}Summary,\n\
             ) -> {pascal}Policy {{\n\
             \x20   let violation_count = summary.violations.len();\n\
             \x20   let mut violations = Vec::new();\n\
             \x20   if options.fail_on_violation() && violation_count > 0 {{\n\
             \x20       violations.push(format!(\"violation_count {{violation_count}} exceeds 0\"));\n\
             \x20   }}\n\n\
             \x20   {pascal}Policy {{\n\
             \x20       fail_on_violation: options.fail_on_violation(),\n\
             \x20       scanned_form_count: summary.scanned_form_count,\n\
             \x20       violation_count,\n\
             \x20       passed: violations.is_empty(),\n\
             \x20       violations,\n\
             \x20   }}\n\
             }}\n\n\
             #[cfg(test)]\n\
             mod tests {{\n\
             \x20   use super::*;\n\n\
             \x20   #[test]\n\
             \x20   fn todo_replace_with_real_fixtures_once_examine_is_implemented() {{\n\
             \x20       let tree = SyntaxTree::parse_with_dialect(\"()\", Dialect::CommonLisp).expect(\"parse\");\n\
             \x20       let (count, violations) =\n\
             \x20           collect_{snake}(&PathBuf::from(\"test.lisp\"), Dialect::CommonLisp, &tree)\n\
             \x20               .expect(\"collect {snake}\");\n\
             \x20       assert_eq!(count, 0);\n\
             \x20       assert!(violations.is_empty(), \"TODO: this stub never finds anything yet\");\n\
             \x20   }}\n\
             }}\n"
        ),
    )?;

    write_new_file(
        &rule_dir.join("usecase.rs"),
        &format!(
            "//! {pascal} ({description}) detection.\n\n\
             pub use crate::{snake}::domain::{{\n\
             \x20   {pascal}Item, {pascal}Policy, {pascal}PolicyOptions, {pascal}Summary, collect_{snake},\n\
             \x20   evaluate_{snake}_policy, summarize_{snake},\n\
             }};\n"
        ),
    )?;

    write_new_file(
        &rule_dir.join("rule.rs"),
        &format!(
            "//! `{kebab}`: TODO — {description}.\n\
             //!\n\
             //! The analysis lives in [`crate::{snake}::domain`], which also backs the\n\
             //! standalone `inspect {kebab}` command; this module only registers it with\n\
             //! the lint suite and phrases its findings.\n\n\
             use paredit_core_lint_engine::LintResult;\n\n\
             use crate::{snake}::domain::examine;\n\
             use paredit_core_lint_engine::engine::{{RuleContext, RuleSink}};\n\
             use paredit_core_lint_engine::model::{{Fixability, HeadFilter, RuleCategory, RuleMeta, Severity}};\n\
             use paredit_core_lint_engine::rule::LintRule;\n\
             use paredit_core_syntax::sexpr::ExpressionView;\n\n\
             pub const META: RuleMeta = RuleMeta::new(\n\
             \x20   \"{kebab}\",\n\
             \x20   RuleCategory::Suspicious,\n\
             \x20   Severity::Warning,\n\
             \x20   \"{description}\",\n\
             \x20   Fixability::ReportOnly,\n\
             );\n\n\
             #[derive(Debug)]\n\
             pub struct Rule;\n\n\
             pub const RULE: Rule = Rule;\n\n\
             impl LintRule for Rule {{\n\
             \x20   fn head_filter(&self) -> HeadFilter {{\n\
             \x20       // TODO: narrow this to `HeadFilter::Heads(&[...])` once `examine` only\n\
             \x20       // cares about specific list heads — `AllNodes` costs a call per node.\n\
             \x20       HeadFilter::AllNodes\n\
             \x20   }}\n\n\
             \x20   fn check(\n\
             \x20       &self,\n\
             \x20       context: &RuleContext<'_>,\n\
             \x20       view: &ExpressionView,\n\
             \x20       sink: &mut RuleSink<'_, '_>,\n\
             \x20   ) -> LintResult<()> {{\n\
             \x20       let mut scanned_form_count = 0;\n\
             \x20       let mut items = Vec::new();\n\
             \x20       examine(view, context.path(), &mut scanned_form_count, &mut items);\n\
             \x20       for item in items {{\n\
             \x20           sink.report(item.span, \"TODO: describe the violation\".to_owned());\n\
             \x20       }}\n\
             \x20       Ok(())\n\
             \x20   }}\n\
             }}\n"
        ),
    )?;

    write_new_file(
        &rule_dir.join("cli").join("mod.rs"),
        "pub mod args;\nmod render;\npub mod workflow;\n",
    )?;

    write_new_file(
        &rule_dir.join("cli").join("args.rs"),
        &format!(
            "use std::path::PathBuf;\n\n\
             use clap::Args;\n\n\
             use paredit_core_cli::args::{{DialectArg, OutputFormat}};\n\n\
             #[derive(Debug, Args)]\n\
             pub struct {pascal}ReportArgs {{\n\
             \x20   /// Files or directories to scan.\n\
             \x20   #[arg(required = true)]\n\
             \x20   pub files: Vec<PathBuf>,\n\
             \x20   /// Override extension-based dialect detection for every file.\n\
             \x20   #[arg(long)]\n\
             \x20   pub dialect: Option<DialectArg>,\n\
             \x20   /// Exit with failure when any violation is found.\n\
             \x20   #[arg(long)]\n\
             \x20   pub fail_on_violation: bool,\n\
             \x20   /// Output format for agent consumption.\n\
             \x20   #[arg(long, value_enum, default_value_t = OutputFormat::Json)]\n\
             \x20   pub output: OutputFormat,\n\
             }}\n"
        ),
    )?;

    write_new_file(
        &rule_dir.join("cli").join("render.rs"),
        &format!(
            "use paredit_core_cli::CliResult;\n\
             use paredit_core_cli::safe_text;\n\
             use serde_json::json;\n\n\
             use crate::{snake}::usecase::{{{pascal}Policy, {pascal}Summary}};\n\
             use paredit_core_cli::args::OutputFormat;\n\n\
             pub fn print_{snake}_report(\n\
             \x20   summary: &{pascal}Summary,\n\
             \x20   policy: &{pascal}Policy,\n\
             \x20   output: OutputFormat,\n\
             ) -> CliResult<()> {{\n\
             \x20   match output {{\n\
             \x20       OutputFormat::Text => {{\n\
             \x20           println!(\"scanned_form_count\\t{{}}\", summary.scanned_form_count);\n\
             \x20           println!(\"violation_count\\t{{}}\", summary.violations.len());\n\
             \x20           if policy.fail_on_violation {{\n\
             \x20               println!(\"policy\\tfail_on_violation=true\\tpassed={{}}\", policy.passed);\n\
             \x20           }}\n\
             \x20           for item in &summary.violations {{\n\
             \x20               println!(\n\
             \x20                   \"violation\\t{{}}\\t{{}}\",\n\
             \x20                   safe_text!(item.path.display()),\n\
             \x20                   item.span.start().get(),\n\
             \x20               );\n\
             \x20           }}\n\
             \x20       }}\n\
             \x20       OutputFormat::Json => {{\n\
             \x20           println!(\n\
             \x20               \"{{}}\",\n\
             \x20               serde_json::to_string_pretty(&json!({{\n\
             \x20                   \"schema_version\": 1,\n\
             \x20                   \"scanned_form_count\": summary.scanned_form_count,\n\
             \x20                   \"violation_count\": summary.violations.len(),\n\
             \x20                   \"policy\": {{\n\
             \x20                       \"fail_on_violation\": policy.fail_on_violation,\n\
             \x20                       \"passed\": policy.passed,\n\
             \x20                       \"violations\": &policy.violations,\n\
             \x20                   }},\n\
             \x20                   \"violations\": summary.violations\n\
             \x20                       .iter()\n\
             \x20                       .map(|item| json!({{\n\
             \x20                           \"path\": item.path.display().to_string(),\n\
             \x20                           \"span\": {{\n\
             \x20                               \"start\": item.span.start().get(),\n\
             \x20                               \"end\": item.span.end().get(),\n\
             \x20                           }},\n\
             \x20                       }}))\n\
             \x20                       .collect::<Vec<_>>(),\n\
             \x20               }}))?\n\
             \x20           );\n\
             \x20       }}\n\
             \x20   }}\n\n\
             \x20   Ok(())\n\
             }}\n"
        ),
    )?;

    write_new_file(
        &rule_dir.join("cli").join("workflow.rs"),
        &format!(
            "use paredit_core_cli::CommandResult;\n\n\
             use crate::{snake}::cli::args::{pascal}ReportArgs;\n\
             use crate::{snake}::cli::render::print_{snake}_report;\n\
             use crate::{snake}::usecase::{{\n\
             \x20   {pascal}PolicyOptions, collect_{snake}, evaluate_{snake}_policy, summarize_{snake},\n\
             }};\n\
             use paredit_core_cli::shared::{{expand_input_files, read_input_dialect_and_tree}};\n\n\
             pub fn {snake}_report(args: {pascal}ReportArgs) -> CommandResult {{\n\
             \x20   let files = expand_input_files(&args.files, args.dialect)?;\n\n\
             \x20   let mut scanned_form_count = 0;\n\
             \x20   let mut violations = Vec::new();\n\n\
             \x20   for file in &files {{\n\
             \x20       let (_, dialect, tree) = read_input_dialect_and_tree(Some(file.clone()), args.dialect)?;\n\
             \x20       let (file_form_count, file_violations) = collect_{snake}(file, dialect, &tree)?;\n\
             \x20       scanned_form_count += file_form_count;\n\
             \x20       violations.extend(file_violations);\n\
             \x20   }}\n\n\
             \x20   let summary = summarize_{snake}(scanned_form_count, violations);\n\
             \x20   let policy = evaluate_{snake}_policy({pascal}PolicyOptions::new(args.fail_on_violation), &summary);\n\
             \x20   let policy_passed = policy.passed;\n\
             \x20   let policy_message = policy.violations.join(\"; \");\n\n\
             \x20   print_{snake}_report(&summary, &policy, args.output)?;\n\n\
             \x20   if !policy_passed {{\n\
             \x20       return Err(paredit_core_cli::gate::gate_failure(format!(\n\
             \x20           \"{kebab}-report policy failed: {{policy_message}}\"\n\
             \x20       )));\n\
             \x20   }}\n\n\
             \x20   Ok(())\n\
             }}\n"
        ),
    )?;

    insert_sorted_mod_line(
        &package_dir.join("src/lib.rs"),
        &format!("pub mod {snake};"),
    )?;

    let (old_count, new_count) = register_in_registry(repo, &crate_name, &snake)?;
    bump_catalog_counts(repo, false, true)?;

    println!();
    println!(
        "Generated `{snake}` inside {}, and registered it: RULE_COUNT {old_count} -> {new_count} \
         in src/lint/registry/mod.rs, warning_count() assertion bumped to match (this \
         rule's META defaults to Severity::Warning / Fixability::ReportOnly — if you change \
         either, fix the matching assertion in src/lint/registry/catalog.rs by hand).",
        package_dir.display()
    );
    println!("Fill in `domain.rs`'s `examine()` — everything else is plumbing.");

    let args_type = format!("{pascal}ReportArgs");
    let workflow_fn = format!("{snake}_report");
    checklist::print_command_wiring(
        repo,
        &checklist::CommandWiring {
            namespace: Namespace::Inspect,
            leaf: kebab,
            feature_crate: &crate_name,
            module_path: &snake,
            args_type: &args_type,
            variant: &pascal,
            workflow_fn: &workflow_fn,
        },
    )?;

    println!(
        "Also update the rule-count prose (currently {old_count}) in docs/src/reference/api.md, \
         docs/src/reference/architecture.md, docs/src/reference/configuration.md, and the doc comment in \
         tests/cli/determinism_contract.rs — none of them are test-enforced, so nothing catches \
         a stale number there but a reviewer."
    );

    Ok(())
}

fn register_in_registry(repo: &Repo, crate_name: &str, snake: &str) -> Result<(u32, u32)> {
    let path = repo.path("src/lint/registry/mod.rs");
    let mut text = fs::read_to_string(&path).map_err(crate::error::XtaskError::io(format!(
        "read {}",
        path.display()
    )))?;

    let marker = "pub const RULE_COUNT: usize = ";
    let start = text.find(marker).ok_or_else(|| {
        crate::error::XtaskError::refused(format!("`{marker}` not found in {}", path.display()))
    })? + marker.len();
    let end = start
        + text[start..]
            .find(';')
            .ok_or_else(|| crate::error::XtaskError::refused("no `;` after RULE_COUNT value"))?;
    let old_count: u32 = text[start..end]
        .trim()
        .parse()
        .map_err(|_| crate::error::XtaskError::refused("RULE_COUNT value is not a number"))?;
    let new_count = old_count + 1;
    text.replace_range(start..end, &new_count.to_string());

    let insertion = format!(
        "    RuleEntry::new(\n        &{crate_name}::{snake}::rule::META,\n        \
         &{crate_name}::{snake}::rule::RULE,\n    ),\n"
    );
    let closing = text
        .rfind("\n];")
        .ok_or_else(|| crate::error::XtaskError::refused("closing `];` of REGISTRY not found"))?;
    text.insert_str(closing + 1, &insertion);

    fs::write(&path, &text).map_err(crate::error::XtaskError::io(format!(
        "write {}",
        path.display()
    )))?;
    println!("  updated {} (RULE_COUNT, REGISTRY entry)", path.display());
    Ok((old_count, new_count))
}

fn bump_catalog_counts(repo: &Repo, is_fixable: bool, is_warning: bool) -> Result<()> {
    let path = repo.path("src/lint/registry/catalog.rs");
    let mut text = fs::read_to_string(&path).map_err(crate::error::XtaskError::io(format!(
        "read {}",
        path.display()
    )))?;

    text = bump_assert(&text, "assert!(RULE_COUNT == ")?;
    if is_fixable {
        text = bump_assert(&text, "assert!(fixable_count() == ")?;
    }
    if is_warning {
        text = bump_assert(&text, "assert!(warning_count() == ")?;
    }

    fs::write(&path, text).map_err(crate::error::XtaskError::io(format!(
        "write {}",
        path.display()
    )))?;
    println!("  updated {} (pinned-count assertions)", path.display());
    Ok(())
}

fn bump_assert(text: &str, marker: &str) -> Result<String> {
    let start = text
        .find(marker)
        .ok_or_else(|| crate::error::XtaskError::refused(format!("`{marker}` not found")))?
        + marker.len();
    let rest = &text[start..];
    let end_offset = rest
        .find(')')
        .ok_or_else(|| crate::error::XtaskError::refused("no closing `)` after assertion value"))?;
    let old: i64 = rest[..end_offset].trim().parse().map_err(|_| {
        crate::error::XtaskError::refused(format!("`{marker}` value is not a number"))
    })?;
    let mut result = text.to_owned();
    result.replace_range(start..start + end_offset, &(old + 1).to_string());
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    /// A throwaway directory shaped like enough of the real repository root
    /// for `run` to work against, so a hardcoded path drifting out of sync
    /// with the real tree (as `src/domain/lint/registry/*` once did) fails
    /// this test with an I/O error instead of only surfacing when a
    /// contributor runs `cargo xtask new-lint-rule` by hand.
    struct FixtureRepo {
        root: std::path::PathBuf,
    }

    impl Drop for FixtureRepo {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    fn build_fixture_repo() -> FixtureRepo {
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let unique = COUNTER.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!(
            "xtask-new-lint-rule-test-{}-{unique}",
            std::process::id()
        ));

        let package_dir = root.join("packages/feature/lint-demo");
        fs::create_dir_all(package_dir.join("src")).expect("create package dir");
        fs::write(
            package_dir.join("Cargo.toml"),
            "[package]\nname = \"paredit_feature_lint_demo\"\n",
        )
        .expect("write package Cargo.toml");
        fs::write(package_dir.join("src/lib.rs"), "pub mod placeholder;\n")
            .expect("write package lib.rs");

        fs::create_dir_all(root.join("src/lint/registry")).expect("create registry dir");
        fs::write(
            root.join("src/lint/registry/mod.rs"),
            "pub const RULE_COUNT: usize = 1;\n\n\
             pub const REGISTRY: &[RuleEntry] = &[\n\
             \x20   RuleEntry::new(&existing::rule::META, &existing::rule::RULE),\n\
             ];\n",
        )
        .expect("write registry mod.rs");
        fs::write(
            root.join("src/lint/registry/catalog.rs"),
            "const _: () = assert!(RULE_COUNT == 1);\n\
             const _: () = assert!(fixable_count() == 0);\n\
             const _: () = assert!(warning_count() == 1);\n",
        )
        .expect("write registry catalog.rs");

        fs::create_dir_all(root.join("src/presentation/cli")).expect("create presentation dir");
        fs::write(root.join("src/presentation/cli/contract.rs"), "")
            .expect("write contract.rs stub");
        fs::create_dir_all(root.join("tests/cli")).expect("create tests/cli dir");
        fs::write(root.join("tests/cli/dialect_contract.rs"), "")
            .expect("write dialect_contract.rs stub");

        FixtureRepo { root }
    }

    #[test]
    fn scaffolds_a_rule_and_bumps_the_registry_against_the_real_path_shape() {
        let fixture = build_fixture_repo();
        let repo = Repo::for_test(fixture.root.clone());
        let options = NewLintRuleOptions {
            theme: "demo".to_owned(),
            name: Name::parse("char-case-fold").expect("valid rule name"),
            description: "flags a suspicious case fold".to_owned(),
        };

        run(&repo, &options).expect("scaffolding must succeed against a well-formed fixture repo");

        let rule_dir = fixture
            .root
            .join("packages/feature/lint-demo/src/char_case_fold");
        assert!(rule_dir.join("mod.rs").is_file());
        assert!(rule_dir.join("domain.rs").is_file());
        assert!(rule_dir.join("usecase.rs").is_file());
        assert!(rule_dir.join("rule.rs").is_file());
        assert!(rule_dir.join("cli").join("args.rs").is_file());

        let registry = fs::read_to_string(fixture.root.join("src/lint/registry/mod.rs"))
            .expect("read bumped registry mod.rs");
        assert!(registry.contains("pub const RULE_COUNT: usize = 2;"));
        assert!(registry.contains("paredit_feature_lint_demo::char_case_fold::rule::META"));

        let catalog = fs::read_to_string(fixture.root.join("src/lint/registry/catalog.rs"))
            .expect("read bumped registry catalog.rs");
        assert!(catalog.contains("assert!(RULE_COUNT == 2)"));
        assert!(catalog.contains("assert!(warning_count() == 2)"));
        assert!(catalog.contains("assert!(fixable_count() == 0)"));
    }
}
