//! `cargo xtask new-command` — scaffolds one command inside an existing
//! feature package: the `domain`/`usecase` pair and the four-file `cli`
//! module (`args`, `render`, `workflow`, `mod`), in the shape every other
//! report-style command in this workspace already uses.
//!
//! It does not touch the composition root (`src/presentation/cli/*.rs`,
//! `tests/cli/dialect_contract.rs`, `docs/src/reference/api.md`) — see
//! `crate::checklist` for why those are printed instead of edited.

use crate::error::Result;

use crate::case::Name;
use crate::checklist::{self, Namespace};
use crate::fs_util::{insert_sorted_mod_line, write_new_file};
use crate::repo::Repo;

pub struct NewCommandOptions {
    pub namespace: Namespace,
    pub package: String,
    pub name: Name,
    pub description: String,
}

pub fn run(repo: &Repo, options: &NewCommandOptions) -> Result<()> {
    let package_dir = repo.feature_package(&options.package)?;
    let crate_name = format!("paredit_feature_{}", options.package.replace('-', "_"));
    let snake = options.name.snake();
    let pascal = options.name.pascal();
    let kebab = options.name.kebab();
    let description = &options.description;
    let module_dir = package_dir.join("src").join(&snake);

    if module_dir.exists() {
        return Err(crate::error::XtaskError::refused(format!(
            "{} already exists",
            module_dir.display()
        )));
    }

    write_new_file(
        &module_dir.join("mod.rs"),
        &format!(
            "//! `{kebab}`: TODO — {description}.\n\
             //!\n\
             //! Generated by `cargo xtask new-command`. See `domain.rs` for the analysis to \
             fill in.\n\n\
             pub mod cli;\n\
             pub mod domain;\n\
             pub mod usecase;\n"
        ),
    )?;

    write_new_file(
        &module_dir.join("domain.rs"),
        &format!(
            "//! `{kebab}` analysis: TODO — {description}.\n\n\
             use std::path::{{Path, PathBuf}};\n\n\
             use paredit_core_cli::CliResult;\n\
             use paredit_core_syntax::dialect::Dialect;\n\
             use paredit_core_syntax::sexpr::SyntaxTree;\n\n\
             #[derive(Debug, Clone)]\n\
             pub struct {pascal}Item {{\n\
             \x20   pub path: PathBuf,\n\
             }}\n\n\
             #[derive(Debug)]\n\
             pub struct {pascal}Summary {{\n\
             \x20   pub items: Vec<{pascal}Item>,\n\
             }}\n\n\
             /// TODO: replace with the real analysis for {description}.\n\
             pub fn analyze(path: &Path, _dialect: Dialect, _tree: &SyntaxTree) -> CliResult<Vec<{pascal}Item>> {{\n\
             \x20   let _ = path;\n\
             \x20   Ok(Vec::new())\n\
             }}\n\n\
             #[must_use]\n\
             pub fn summarize(items: Vec<{pascal}Item>) -> {pascal}Summary {{\n\
             \x20   {pascal}Summary {{ items }}\n\
             }}\n\n\
             #[cfg(test)]\n\
             mod tests {{\n\
             \x20   use super::*;\n\n\
             \x20   #[test]\n\
             \x20   fn todo_replace_with_a_real_assertion() {{\n\
             \x20       let tree = SyntaxTree::parse_with_dialect(\"()\", Dialect::CommonLisp).expect(\"parse\");\n\
             \x20       let items = analyze(Path::new(\"test.lisp\"), Dialect::CommonLisp, &tree).expect(\"analyze\");\n\
             \x20       assert!(items.is_empty(), \"TODO: this stub never finds anything yet\");\n\
             \x20   }}\n\
             }}\n"
        ),
    )?;

    write_new_file(
        &module_dir.join("usecase.rs"),
        &format!(
            "//! Re-exports [`crate::{snake}::domain`] for the cli layer, matching the rest \
             of the suite's shape.\n\n\
             pub use crate::{snake}::domain::{{{pascal}Item, {pascal}Summary, analyze, summarize}};\n"
        ),
    )?;

    write_new_file(
        &module_dir.join("cli").join("mod.rs"),
        "pub mod args;\nmod render;\npub mod workflow;\n",
    )?;

    write_new_file(
        &module_dir.join("cli").join("args.rs"),
        &format!(
            "use std::path::PathBuf;\n\n\
             use clap::Args;\n\n\
             use paredit_core_cli::args::{{DialectArg, OutputFormat}};\n\n\
             #[derive(Debug, Args)]\n\
             pub struct {pascal}Args {{\n\
             \x20   /// Files or directories to scan.\n\
             \x20   #[arg(required = true)]\n\
             \x20   pub files: Vec<PathBuf>,\n\
             \x20   /// Override extension-based dialect detection for every file.\n\
             \x20   #[arg(long)]\n\
             \x20   pub dialect: Option<DialectArg>,\n\
             \x20   /// Output format for agent consumption.\n\
             \x20   #[arg(long, value_enum, default_value_t = OutputFormat::Json)]\n\
             \x20   pub output: OutputFormat,\n\
             }}\n"
        ),
    )?;

    write_new_file(
        &module_dir.join("cli").join("render.rs"),
        &format!(
            "use paredit_core_cli::CliResult;\n\
             use serde_json::json;\n\n\
             use crate::{snake}::usecase::{pascal}Summary;\n\
             use paredit_core_cli::args::OutputFormat;\n\n\
             pub fn print_{snake}_report(summary: &{pascal}Summary, output: OutputFormat) -> CliResult<()> {{\n\
             \x20   match output {{\n\
             \x20       OutputFormat::Text => {{\n\
             \x20           println!(\"item_count\\t{{}}\", summary.items.len());\n\
             \x20       }}\n\
             \x20       OutputFormat::Json => {{\n\
             \x20           println!(\n\
             \x20               \"{{}}\",\n\
             \x20               serde_json::to_string_pretty(&json!({{\n\
             \x20                   \"schema_version\": 1,\n\
             \x20                   \"item_count\": summary.items.len(),\n\
             \x20               }}))?\n\
             \x20           );\n\
             \x20       }}\n\
             \x20   }}\n\
             \x20   Ok(())\n\
             }}\n"
        ),
    )?;

    write_new_file(
        &module_dir.join("cli").join("workflow.rs"),
        &format!(
            "use paredit_core_cli::CommandResult;\n\n\
             use crate::{snake}::cli::args::{pascal}Args;\n\
             use crate::{snake}::cli::render::print_{snake}_report;\n\
             use crate::{snake}::usecase::{{analyze, summarize}};\n\
             use paredit_core_cli::shared::{{expand_input_files, read_input_dialect_and_tree}};\n\n\
             pub fn {snake}_report(args: {pascal}Args) -> CommandResult {{\n\
             \x20   let files = expand_input_files(&args.files, args.dialect)?;\n\n\
             \x20   let mut items = Vec::new();\n\
             \x20   for file in &files {{\n\
             \x20       let (_, dialect, tree) = read_input_dialect_and_tree(Some(file.clone()), args.dialect)?;\n\
             \x20       items.extend(analyze(file, dialect, &tree)?);\n\
             \x20   }}\n\n\
             \x20   let summary = summarize(items);\n\
             \x20   print_{snake}_report(&summary, args.output)?;\n\n\
             \x20   Ok(())\n\
             }}\n"
        ),
    )?;

    insert_sorted_mod_line(
        &package_dir.join("src/lib.rs"),
        &format!("pub mod {snake};"),
    )?;

    println!();
    println!(
        "Generated `{}` inside {}. Fill in `domain.rs`'s `analyze()` — everything else is \
         plumbing.",
        snake,
        package_dir.display()
    );

    let args_type = format!("{pascal}Args");
    let workflow_fn = format!("{snake}_report");
    checklist::print_command_wiring(
        repo,
        &checklist::CommandWiring {
            namespace: options.namespace,
            leaf: kebab,
            feature_crate: &crate_name,
            module_path: &snake,
            args_type: &args_type,
            variant: &pascal,
            workflow_fn: &workflow_fn,
        },
    )?;

    Ok(())
}
