//! The one place a lint rule is registered.
//!
//! `RULES`, `RULE_DOCS`, `FIXABLE_RULES`, and `WARNING_RULES` used to be four
//! hand-maintained parallel arrays that a new rule had to be threaded through
//! in lockstep. They are now derived from this array at compile time (see
//! [`catalog`]), so the only way to add a rule is to add its module and one
//! line here — and the only way for the catalogue to disagree with itself is
//! for the derivation to be wrong, which a `const` assertion catches.

pub mod catalog;

use super::rule::RuleEntry;

/// How many rules the suite ships. Pinned so that adding or losing a rule is a
/// deliberate, reviewed change rather than a silent drift in the catalogue.
pub const RULE_COUNT: usize = 174;

/// Every rule, in report order: findings are grouped by this order, and the
/// public `RULES`/`RULE_DOCS` arrays preserve it.
pub const REGISTRY: [RuleEntry; RULE_COUNT] = [
    RuleEntry::new(
        &paredit_feature_lint_form_shape::self_assignment::rule::META,
        &paredit_feature_lint_form_shape::self_assignment::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_setf_places::rule::META,
        &paredit_feature_lint_form_shape::duplicate_setf_places::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::setf_arity::rule::META,
        &paredit_feature_lint_form_shape::setf_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::setq_non_variable::rule::META,
        &paredit_feature_lint_form_shape::setq_non_variable::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_incf::rule::META,
        &paredit_feature_lint_form_shape::manual_incf::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_push::rule::META,
        &paredit_feature_lint_form_shape::manual_push::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_pushnew::rule::META,
        &paredit_feature_lint_form_shape::manual_pushnew::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::explicit_step_delta::rule::META,
        &paredit_feature_lint_numeric::explicit_step_delta::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::negated_step_delta::rule::META,
        &paredit_feature_lint_numeric::negated_step_delta::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::explicit_nil_return::rule::META,
        &paredit_feature_lint_control_flow::explicit_nil_return::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::cons_to_list::rule::META,
        &paredit_feature_lint_sequence::cons_to_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::double_reverse::rule::META,
        &paredit_feature_lint_sequence::double_reverse::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::modify_macro_arity::rule::META,
        &paredit_feature_lint_numeric::modify_macro_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_parameters::rule::META,
        &paredit_feature_lint_form_shape::duplicate_parameters::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_lambda_list_keyword::rule::META,
        &paredit_feature_lint_form_shape::duplicate_lambda_list_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::lambda_list_keyword_order::rule::META,
        &paredit_feature_lint_form_shape::lambda_list_keyword_order::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_quote::rule::META,
        &paredit_feature_lint_form_shape::redundant_quote::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_progn::rule::META,
        &paredit_feature_lint_control_flow::redundant_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::nested_progn::rule::META,
        &paredit_feature_lint_control_flow::nested_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_when::rule::META,
        &paredit_feature_lint_conditional::nested_when::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_unless::rule::META,
        &paredit_feature_lint_conditional::nested_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_boolean::rule::META,
        &paredit_feature_lint_conditional::nested_boolean::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::nested_cxr::rule::META,
        &paredit_feature_lint_form_shape::nested_cxr::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nth_constant_index::rule::META,
        &paredit_feature_lint_sequence::nth_constant_index::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nthcdr_zero::rule::META,
        &paredit_feature_lint_sequence::nthcdr_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nthcdr_small_index::rule::META,
        &paredit_feature_lint_sequence::nthcdr_small_index::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_body_progn::rule::META,
        &paredit_feature_lint_control_flow::redundant_body_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::empty_let::rule::META,
        &paredit_feature_lint_form_shape::empty_let::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::redundant_if_nil::rule::META,
        &paredit_feature_lint_conditional::redundant_if_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_let_star::rule::META,
        &paredit_feature_lint_form_shape::redundant_let_star::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_funcall::rule::META,
        &paredit_feature_lint_form_shape::redundant_funcall::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_the::rule::META,
        &paredit_feature_lint_form_shape::redundant_the::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::funcall_lambda::rule::META,
        &paredit_feature_lint_form_shape::funcall_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::sharp_quoted_lambda::rule::META,
        &paredit_feature_lint_form_shape::sharp_quoted_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_identity::rule::META,
        &paredit_feature_lint_form_shape::redundant_identity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_apply::rule::META,
        &paredit_feature_lint_form_shape::redundant_apply::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_eql_test::rule::META,
        &paredit_feature_lint_sequence::redundant_eql_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_identity_key::rule::META,
        &paredit_feature_lint_sequence::redundant_identity_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_when_unless::rule::META,
        &paredit_feature_lint_conditional::negated_when_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_comparison::rule::META,
        &paredit_feature_lint_conditional::negated_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_if::rule::META,
        &paredit_feature_lint_conditional::negated_if::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_to_or::rule::META,
        &paredit_feature_lint_conditional::if_to_or::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_not::rule::META,
        &paredit_feature_lint_conditional::if_not::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::one_step_arithmetic::rule::META,
        &paredit_feature_lint_numeric::one_step_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::one_armed_if::rule::META,
        &paredit_feature_lint_conditional::one_armed_if::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::self_comparison::rule::META,
        &paredit_feature_lint_numeric::self_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::nil_comparison::rule::META,
        &paredit_feature_lint_numeric::nil_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::t_comparison::rule::META,
        &paredit_feature_lint_numeric::t_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::identical_if_branches::rule::META,
        &paredit_feature_lint_conditional::identical_if_branches::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::constant_if_test::rule::META,
        &paredit_feature_lint_conditional::constant_if_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::constant_when_test::rule::META,
        &paredit_feature_lint_conditional::constant_when_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_arity::rule::META,
        &paredit_feature_lint_conditional::if_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::the_arity::rule::META,
        &paredit_feature_lint_form_shape::the_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::equality_arity::rule::META,
        &paredit_feature_lint_numeric::equality_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::accessor_arity::rule::META,
        &paredit_feature_lint_sequence::accessor_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::append_list_to_cons::rule::META,
        &paredit_feature_lint_sequence::append_list_to_cons::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_to_string::rule::META,
        &paredit_feature_lint_string_char::format_to_string::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_newline::rule::META,
        &paredit_feature_lint_string_char::format_newline::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::redundant_divisor::rule::META,
        &paredit_feature_lint_numeric::redundant_divisor::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_case_keys::rule::META,
        &paredit_feature_lint_conditional::duplicate_case_keys::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::quoted_case_key::rule::META,
        &paredit_feature_lint_conditional::quoted_case_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::case_nil_key::rule::META,
        &paredit_feature_lint_conditional::case_nil_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::typecase_nil_key::rule::META,
        &paredit_feature_lint_conditional::typecase_nil_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::malformed_case_clause::rule::META,
        &paredit_feature_lint_conditional::malformed_case_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::unreachable_case_clause::rule::META,
        &paredit_feature_lint_conditional::unreachable_case_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::exhaustive_case_otherwise::rule::META,
        &paredit_feature_lint_conditional::exhaustive_case_otherwise::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_cond_tests::rule::META,
        &paredit_feature_lint_conditional::duplicate_cond_tests::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::unreachable_cond_clause::rule::META,
        &paredit_feature_lint_conditional::unreachable_cond_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::malformed_cond_clause::rule::META,
        &paredit_feature_lint_conditional::malformed_cond_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_let_bindings::rule::META,
        &paredit_feature_lint_form_shape::duplicate_let_bindings::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::malformed_let_binding::rule::META,
        &paredit_feature_lint_form_shape::malformed_let_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::binds_constant::rule::META,
        &paredit_feature_lint_control_flow::binds_constant::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::malformed_iteration_spec::rule::META,
        &paredit_feature_lint_control_flow::malformed_iteration_spec::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::eval_when_situation::rule::META,
        &paredit_feature_lint_control_flow::eval_when_situation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_boolean_operands::rule::META,
        &paredit_feature_lint_conditional::duplicate_boolean_operands::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::dead_boolean_operand::rule::META,
        &paredit_feature_lint_conditional::dead_boolean_operand::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::redundant_boolean_identity::rule::META,
        &paredit_feature_lint_conditional::redundant_boolean_identity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::de_morgan::rule::META,
        &paredit_feature_lint_conditional::de_morgan::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::single_operand_boolean::rule::META,
        &paredit_feature_lint_conditional::single_operand_boolean::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::single_operand_list_op::rule::META,
        &paredit_feature_lint_sequence::single_operand_list_op::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::single_operand_arithmetic::rule::META,
        &paredit_feature_lint_numeric::single_operand_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eql_string_comparison::rule::META,
        &paredit_feature_lint_numeric::eql_string_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eql_list_comparison::rule::META,
        &paredit_feature_lint_numeric::eql_list_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::eql_search_literal::rule::META,
        &paredit_feature_lint_sequence::eql_search_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eq_number_comparison::rule::META,
        &paredit_feature_lint_numeric::eq_number_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eq_char_comparison::rule::META,
        &paredit_feature_lint_numeric::eq_char_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::single_arg_comparison::rule::META,
        &paredit_feature_lint_numeric::single_arg_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::sign_comparison::rule::META,
        &paredit_feature_lint_numeric::sign_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::single_clause_cond::rule::META,
        &paredit_feature_lint_conditional::single_clause_cond::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::cond_t_clause::rule::META,
        &paredit_feature_lint_conditional::cond_t_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::single_value_bind::rule::META,
        &paredit_feature_lint_form_shape::single_value_bind::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_missing_destination::rule::META,
        &paredit_feature_lint_string_char::format_missing_destination::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::literal_place::rule::META,
        &paredit_feature_lint_numeric::literal_place::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::destructive_literal::rule::META,
        &paredit_feature_lint_sequence::destructive_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::char_op_string::rule::META,
        &paredit_feature_lint_string_char::char_op_string::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::empty_body::rule::META,
        &paredit_feature_lint_conditional::empty_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::identity_arithmetic::rule::META,
        &paredit_feature_lint_numeric::identity_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::verbose_negation::rule::META,
        &paredit_feature_lint_numeric::verbose_negation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::list_star_to_cons::rule::META,
        &paredit_feature_lint_sequence::list_star_to_cons::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::values_list_of_list::rule::META,
        &paredit_feature_lint_form_shape::values_list_of_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_prog1::rule::META,
        &paredit_feature_lint_control_flow::redundant_prog1::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::subseq_zero::rule::META,
        &paredit_feature_lint_sequence::subseq_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::car_nthcdr::rule::META,
        &paredit_feature_lint_sequence::car_nthcdr::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::car_reverse::rule::META,
        &paredit_feature_lint_sequence::car_reverse::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::append_nil::rule::META,
        &paredit_feature_lint_sequence::append_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::multiple_value_list_of_values::rule::META,
        &paredit_feature_lint_form_shape::multiple_value_list_of_values::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::typep_predicate::rule::META,
        &paredit_feature_lint_form_shape::typep_predicate::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::coerce_to_t::rule::META,
        &paredit_feature_lint_form_shape::coerce_to_t::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::gethash_default::rule::META,
        &paredit_feature_lint_form_shape::gethash_default::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_hash_table_test::rule::META,
        &paredit_feature_lint_form_shape::make_hash_table_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::zero_divisor::rule::META,
        &paredit_feature_lint_numeric::zero_divisor::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_keyword::rule::META,
        &paredit_feature_lint_form_shape::duplicate_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::defpackage_quoted::rule::META,
        &paredit_feature_lint_form_shape::defpackage_quoted::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::step_zero::rule::META,
        &paredit_feature_lint_numeric::step_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_to_unless::rule::META,
        &paredit_feature_lint_conditional::if_to_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::prog2_to_progn::rule::META,
        &paredit_feature_lint_control_flow::prog2_to_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::handler_case_no_clauses::rule::META,
        &paredit_feature_lint_control_flow::handler_case_no_clauses::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::unwind_protect_no_cleanup::rule::META,
        &paredit_feature_lint_control_flow::unwind_protect_no_cleanup::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_start_zero::rule::META,
        &paredit_feature_lint_sequence::redundant_start_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_end_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_end_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_from_end_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_from_end_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_count_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_count_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::string_case_fold::rule::META,
        &paredit_feature_lint_string_char::string_case_fold::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::char_case_fold::rule::META,
        &paredit_feature_lint_string_char::char_case_fold::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::nested_string_case::rule::META,
        &paredit_feature_lint_string_char::nested_string_case::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::code_char_char_code::rule::META,
        &paredit_feature_lint_string_char::code_char_char_code::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::last_default_count::rule::META,
        &paredit_feature_lint_sequence::last_default_count::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::butlast_default_count::rule::META,
        &paredit_feature_lint_form_shape::butlast_default_count::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_list_default_element::rule::META,
        &paredit_feature_lint_form_shape::make_list_default_element::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::parse_integer_default_radix::rule::META,
        &paredit_feature_lint_form_shape::parse_integer_default_radix::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::getf_default_nil::rule::META,
        &paredit_feature_lint_form_shape::getf_default_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_array_default_keyword::rule::META,
        &paredit_feature_lint_form_shape::make_array_default_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::nested_char_case::rule::META,
        &paredit_feature_lint_form_shape::nested_char_case::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::list_star_nil::rule::META,
        &paredit_feature_lint_sequence::list_star_nil::rule::RULE,
    ),
    // Cost, not correctness: every rule below flags code that works and works
    // more slowly than the alternative its message names.
    RuleEntry::new(
        &paredit_feature_lint_performance::length_emptiness_test::META,
        &paredit_feature_lint_performance::length_emptiness_test::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::quadratic_accumulation::META,
        &paredit_feature_lint_performance::quadratic_accumulation::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::linear_search_in_loop::META,
        &paredit_feature_lint_performance::linear_search_in_loop::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::unnecessary_copy::META,
        &paredit_feature_lint_performance::unnecessary_copy::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::copy_before_destructive::META,
        &paredit_feature_lint_performance::copy_before_destructive::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::loop_invariant_allocation::META,
        &paredit_feature_lint_performance::loop_invariant_allocation::RULE,
    ),
    // What the code assumes about where it runs.
    RuleEntry::new(
        &paredit_feature_lint_portability::implementation_package_symbol::META,
        &paredit_feature_lint_portability::implementation_package_symbol::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::unportable_pathname::META,
        &paredit_feature_lint_portability::unportable_pathname::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::ascii_code_char::META,
        &paredit_feature_lint_portability::ascii_code_char::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::float_equality::META,
        &paredit_feature_lint_portability::float_equality::RULE,
    ),
    // Shared state, untrusted input, leaked resources, swallowed errors: every
    // rule below reports a form whose defect is only visible one level out.
    RuleEntry::new(
        &paredit_feature_lint_safety::global_mutation_in_function::META,
        &paredit_feature_lint_safety::global_mutation_in_function::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::check_then_act::META,
        &paredit_feature_lint_safety::check_then_act::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::eval_of_non_constant::META,
        &paredit_feature_lint_safety::eval_of_non_constant::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::read_without_read_eval_guard::META,
        &paredit_feature_lint_safety::read_without_read_eval_guard::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::subprocess_string_building::META,
        &paredit_feature_lint_safety::subprocess_string_building::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::unclosed_stream::META,
        &paredit_feature_lint_safety::unclosed_stream::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::stream_escapes_with_open_file::META,
        &paredit_feature_lint_safety::stream_escapes_with_open_file::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::handler_case_swallows_error::META,
        &paredit_feature_lint_safety::handler_case_swallows_error::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::unreachable_handler_clause::META,
        &paredit_feature_lint_safety::unreachable_handler_clause::RULE,
    ),
    // What a definition says about itself: its name, its docstring, its
    // declarations, and its CLOS options.
    RuleEntry::new(
        &paredit_feature_lint_convention::definition_naming::META,
        &paredit_feature_lint_convention::definition_naming::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::destructive_function_naming::META,
        &paredit_feature_lint_convention::destructive_function_naming::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::missing_docstring::META,
        &paredit_feature_lint_convention::missing_docstring::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::ignore_declaration_conflict::META,
        &paredit_feature_lint_convention::ignore_declaration_conflict::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::contradictory_optimize::META,
        &paredit_feature_lint_convention::contradictory_optimize::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::defclass_slot_option::META,
        &paredit_feature_lint_convention::defclass_slot_option::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::method_lambda_list_mismatch::META,
        &paredit_feature_lint_convention::method_lambda_list_mismatch::RULE,
    ),
    // Emacs Lisp. Every rule below declares `Dialect::EmacsLisp` only, so a
    // Common Lisp run skips them before walking anything.
    RuleEntry::new(
        &paredit_feature_emacs_lisp::missing_lexical_binding::rule::META,
        &paredit_feature_emacs_lisp::missing_lexical_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::unreachable_lexical_binding::rule::META,
        &paredit_feature_emacs_lisp::unreachable_lexical_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::autoload_cookie_without_form::rule::META,
        &paredit_feature_emacs_lisp::autoload_cookie_without_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::defcustom_missing_type::rule::META,
        &paredit_feature_emacs_lisp::defcustom_missing_type::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::defcustom_missing_group::rule::META,
        &paredit_feature_emacs_lisp::defcustom_missing_group::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::obsolete_cl_alias::rule::META,
        &paredit_feature_emacs_lisp::obsolete_cl_alias::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::quoted_lambda::rule::META,
        &paredit_feature_emacs_lisp::quoted_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::interactive_in_macro::rule::META,
        &paredit_feature_emacs_lisp::interactive_in_macro::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::condition_case_without_handler::rule::META,
        &paredit_feature_emacs_lisp::condition_case_without_handler::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::embedded_secret::META,
        &paredit_feature_lint_safety::embedded_secret::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::giant_conditional_form::rule::META,
        &paredit_feature_lint_form_shape::giant_conditional_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::effectively_constant_variable::META,
        &paredit_feature_lint_convention::effectively_constant_variable::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::redundant_condition_supertype::META,
        &paredit_feature_lint_convention::redundant_condition_supertype::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::commented_out_code::META,
        &paredit_feature_lint_convention::commented_out_code::RULE,
    ),
];
