//! The one place a lint rule is registered.
//!
//! [`catalog`] derives the rule documentation and fixability/severity indexes
//! from this registry at compile time. Adding a rule therefore requires one
//! registry entry, and const assertions guard the derived catalogue.

pub mod catalog;

use super::rule::RuleEntry;

/// How many rules the suite ships. Pinned so that adding or losing a rule is a
/// deliberate, reviewed change rather than silent catalogue drift.
pub const RULE_COUNT: usize = 358;

/// Every rule, in report order: findings are grouped by this order, and the
/// public `RULES`/`RULE_DOCS` arrays preserve it.
pub const REGISTRY: [RuleEntry; RULE_COUNT] = [
    RuleEntry::new(
        &paredit_feature_lint_form_shape::self_assignment::rule::META,
        &paredit_feature_lint_form_shape::self_assignment::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_setf_places::rule::META,
        &paredit_feature_lint_form_shape::duplicate_setf_places::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::setf_arity::rule::META,
        &paredit_feature_lint_form_shape::setf_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::setq_non_variable::rule::META,
        &paredit_feature_lint_form_shape::setq_non_variable::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_incf::rule::META,
        &paredit_feature_lint_form_shape::manual_incf::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_push::rule::META,
        &paredit_feature_lint_form_shape::manual_push::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::manual_pushnew::rule::META,
        &paredit_feature_lint_form_shape::manual_pushnew::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::explicit_step_delta::rule::META,
        &paredit_feature_lint_numeric::explicit_step_delta::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::negated_step_delta::rule::META,
        &paredit_feature_lint_numeric::negated_step_delta::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::explicit_nil_return::rule::META,
        &paredit_feature_lint_control_flow::explicit_nil_return::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::cons_to_list::rule::META,
        &paredit_feature_lint_sequence::cons_to_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::double_reverse::rule::META,
        &paredit_feature_lint_sequence::double_reverse::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::modify_macro_arity::rule::META,
        &paredit_feature_lint_numeric::modify_macro_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_parameters::rule::META,
        &paredit_feature_lint_form_shape::duplicate_parameters::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_lambda_list_keyword::rule::META,
        &paredit_feature_lint_form_shape::duplicate_lambda_list_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::lambda_list_keyword_order::rule::META,
        &paredit_feature_lint_form_shape::lambda_list_keyword_order::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_quote::rule::META,
        &paredit_feature_lint_form_shape::redundant_quote::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_progn::rule::META,
        &paredit_feature_lint_control_flow::redundant_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::nested_progn::rule::META,
        &paredit_feature_lint_control_flow::nested_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_when::rule::META,
        &paredit_feature_lint_conditional::nested_when::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_unless::rule::META,
        &paredit_feature_lint_conditional::nested_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_boolean::rule::META,
        &paredit_feature_lint_conditional::nested_boolean::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::nested_cxr::rule::META,
        &paredit_feature_lint_form_shape::nested_cxr::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nth_constant_index::rule::META,
        &paredit_feature_lint_sequence::nth_constant_index::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nthcdr_zero::rule::META,
        &paredit_feature_lint_sequence::nthcdr_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nthcdr_small_index::rule::META,
        &paredit_feature_lint_sequence::nthcdr_small_index::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_body_progn::rule::META,
        &paredit_feature_lint_control_flow::redundant_body_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::empty_let::rule::META,
        &paredit_feature_lint_form_shape::empty_let::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::redundant_if_nil::rule::META,
        &paredit_feature_lint_conditional::redundant_if_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_let_star::rule::META,
        &paredit_feature_lint_form_shape::redundant_let_star::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_funcall::rule::META,
        &paredit_feature_lint_form_shape::redundant_funcall::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_the::rule::META,
        &paredit_feature_lint_form_shape::redundant_the::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::funcall_lambda::rule::META,
        &paredit_feature_lint_form_shape::funcall_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::sharp_quoted_lambda::rule::META,
        &paredit_feature_lint_form_shape::sharp_quoted_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_identity::rule::META,
        &paredit_feature_lint_form_shape::redundant_identity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::redundant_apply::rule::META,
        &paredit_feature_lint_form_shape::redundant_apply::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_eql_test::rule::META,
        &paredit_feature_lint_sequence::redundant_eql_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_identity_key::rule::META,
        &paredit_feature_lint_sequence::redundant_identity_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_when_unless::rule::META,
        &paredit_feature_lint_conditional::negated_when_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_comparison::rule::META,
        &paredit_feature_lint_conditional::negated_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::negated_if::rule::META,
        &paredit_feature_lint_conditional::negated_if::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_to_or::rule::META,
        &paredit_feature_lint_conditional::if_to_or::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_not::rule::META,
        &paredit_feature_lint_conditional::if_not::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::one_step_arithmetic::rule::META,
        &paredit_feature_lint_numeric::one_step_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::one_armed_if::rule::META,
        &paredit_feature_lint_conditional::one_armed_if::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::self_comparison::rule::META,
        &paredit_feature_lint_numeric::self_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::nil_comparison::rule::META,
        &paredit_feature_lint_numeric::nil_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::t_comparison::rule::META,
        &paredit_feature_lint_numeric::t_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::identical_if_branches::rule::META,
        &paredit_feature_lint_conditional::identical_if_branches::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::constant_if_test::rule::META,
        &paredit_feature_lint_conditional::constant_if_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::constant_when_test::rule::META,
        &paredit_feature_lint_conditional::constant_when_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_arity::rule::META,
        &paredit_feature_lint_conditional::if_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::the_arity::rule::META,
        &paredit_feature_lint_form_shape::the_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::equality_arity::rule::META,
        &paredit_feature_lint_numeric::equality_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::accessor_arity::rule::META,
        &paredit_feature_lint_sequence::accessor_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::append_list_to_cons::rule::META,
        &paredit_feature_lint_sequence::append_list_to_cons::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_to_string::rule::META,
        &paredit_feature_lint_string_char::format_to_string::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_newline::rule::META,
        &paredit_feature_lint_string_char::format_newline::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::redundant_divisor::rule::META,
        &paredit_feature_lint_numeric::redundant_divisor::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_case_keys::rule::META,
        &paredit_feature_lint_conditional::duplicate_case_keys::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::quoted_case_key::rule::META,
        &paredit_feature_lint_conditional::quoted_case_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::case_nil_key::rule::META,
        &paredit_feature_lint_conditional::case_nil_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::typecase_nil_key::rule::META,
        &paredit_feature_lint_conditional::typecase_nil_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::malformed_case_clause::rule::META,
        &paredit_feature_lint_conditional::malformed_case_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::unreachable_case_clause::rule::META,
        &paredit_feature_lint_conditional::unreachable_case_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::exhaustive_case_otherwise::rule::META,
        &paredit_feature_lint_conditional::exhaustive_case_otherwise::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_cond_tests::rule::META,
        &paredit_feature_lint_conditional::duplicate_cond_tests::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::unreachable_cond_clause::rule::META,
        &paredit_feature_lint_conditional::unreachable_cond_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::malformed_cond_clause::rule::META,
        &paredit_feature_lint_conditional::malformed_cond_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_let_bindings::rule::META,
        &paredit_feature_lint_form_shape::duplicate_let_bindings::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::malformed_let_binding::rule::META,
        &paredit_feature_lint_form_shape::malformed_let_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::binds_constant::rule::META,
        &paredit_feature_lint_control_flow::binds_constant::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::malformed_iteration_spec::rule::META,
        &paredit_feature_lint_control_flow::malformed_iteration_spec::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::eval_when_situation::rule::META,
        &paredit_feature_lint_control_flow::eval_when_situation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::duplicate_boolean_operands::rule::META,
        &paredit_feature_lint_conditional::duplicate_boolean_operands::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::dead_boolean_operand::rule::META,
        &paredit_feature_lint_conditional::dead_boolean_operand::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::redundant_boolean_identity::rule::META,
        &paredit_feature_lint_conditional::redundant_boolean_identity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::de_morgan::rule::META,
        &paredit_feature_lint_conditional::de_morgan::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::single_operand_boolean::rule::META,
        &paredit_feature_lint_conditional::single_operand_boolean::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::single_operand_list_op::rule::META,
        &paredit_feature_lint_sequence::single_operand_list_op::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::single_operand_arithmetic::rule::META,
        &paredit_feature_lint_numeric::single_operand_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eql_string_comparison::rule::META,
        &paredit_feature_lint_numeric::eql_string_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eql_list_comparison::rule::META,
        &paredit_feature_lint_numeric::eql_list_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::eql_search_literal::rule::META,
        &paredit_feature_lint_sequence::eql_search_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eq_number_comparison::rule::META,
        &paredit_feature_lint_numeric::eq_number_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::eq_char_comparison::rule::META,
        &paredit_feature_lint_numeric::eq_char_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::single_arg_comparison::rule::META,
        &paredit_feature_lint_numeric::single_arg_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::sign_comparison::rule::META,
        &paredit_feature_lint_numeric::sign_comparison::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::single_clause_cond::rule::META,
        &paredit_feature_lint_conditional::single_clause_cond::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::cond_t_clause::rule::META,
        &paredit_feature_lint_conditional::cond_t_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::single_value_bind::rule::META,
        &paredit_feature_lint_form_shape::single_value_bind::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_missing_destination::rule::META,
        &paredit_feature_lint_string_char::format_missing_destination::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::literal_place::rule::META,
        &paredit_feature_lint_numeric::literal_place::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::destructive_literal::rule::META,
        &paredit_feature_lint_sequence::destructive_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::char_op_string::rule::META,
        &paredit_feature_lint_string_char::char_op_string::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::empty_body::rule::META,
        &paredit_feature_lint_conditional::empty_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::identity_arithmetic::rule::META,
        &paredit_feature_lint_numeric::identity_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::verbose_negation::rule::META,
        &paredit_feature_lint_numeric::verbose_negation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::list_star_to_cons::rule::META,
        &paredit_feature_lint_sequence::list_star_to_cons::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::values_list_of_list::rule::META,
        &paredit_feature_lint_form_shape::values_list_of_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::redundant_prog1::rule::META,
        &paredit_feature_lint_control_flow::redundant_prog1::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::subseq_zero::rule::META,
        &paredit_feature_lint_sequence::subseq_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::car_nthcdr::rule::META,
        &paredit_feature_lint_sequence::car_nthcdr::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::car_reverse::rule::META,
        &paredit_feature_lint_sequence::car_reverse::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::append_nil::rule::META,
        &paredit_feature_lint_sequence::append_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::multiple_value_list_of_values::rule::META,
        &paredit_feature_lint_form_shape::multiple_value_list_of_values::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::typep_predicate::rule::META,
        &paredit_feature_lint_form_shape::typep_predicate::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::coerce_to_t::rule::META,
        &paredit_feature_lint_form_shape::coerce_to_t::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::gethash_default::rule::META,
        &paredit_feature_lint_form_shape::gethash_default::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_hash_table_test::rule::META,
        &paredit_feature_lint_form_shape::make_hash_table_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::zero_divisor::rule::META,
        &paredit_feature_lint_numeric::zero_divisor::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::duplicate_keyword::rule::META,
        &paredit_feature_lint_form_shape::duplicate_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::defpackage_quoted::rule::META,
        &paredit_feature_lint_form_shape::defpackage_quoted::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::step_zero::rule::META,
        &paredit_feature_lint_numeric::step_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::if_to_unless::rule::META,
        &paredit_feature_lint_conditional::if_to_unless::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::prog2_to_progn::rule::META,
        &paredit_feature_lint_control_flow::prog2_to_progn::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::handler_case_no_clauses::rule::META,
        &paredit_feature_lint_control_flow::handler_case_no_clauses::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::unwind_protect_no_cleanup::rule::META,
        &paredit_feature_lint_control_flow::unwind_protect_no_cleanup::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_start_zero::rule::META,
        &paredit_feature_lint_sequence::redundant_start_zero::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_end_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_end_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_from_end_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_from_end_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_count_nil::rule::META,
        &paredit_feature_lint_sequence::redundant_count_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::string_case_fold::rule::META,
        &paredit_feature_lint_string_char::string_case_fold::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::char_case_fold::rule::META,
        &paredit_feature_lint_string_char::char_case_fold::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::nested_string_case::rule::META,
        &paredit_feature_lint_string_char::nested_string_case::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::code_char_char_code::rule::META,
        &paredit_feature_lint_string_char::code_char_char_code::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::last_default_count::rule::META,
        &paredit_feature_lint_sequence::last_default_count::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::butlast_default_count::rule::META,
        &paredit_feature_lint_form_shape::butlast_default_count::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_list_default_element::rule::META,
        &paredit_feature_lint_form_shape::make_list_default_element::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::parse_integer_default_radix::rule::META,
        &paredit_feature_lint_form_shape::parse_integer_default_radix::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::getf_default_nil::rule::META,
        &paredit_feature_lint_form_shape::getf_default_nil::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::make_array_default_keyword::rule::META,
        &paredit_feature_lint_form_shape::make_array_default_keyword::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::nested_char_case::rule::META,
        &paredit_feature_lint_form_shape::nested_char_case::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::list_star_nil::rule::META,
        &paredit_feature_lint_sequence::list_star_nil::rule::RULE,
    ),
    // Cost, not correctness: every rule below flags code that works and works
    // more slowly than the alternative its message names.
    RuleEntry::new(
        &paredit_feature_lint_performance::length_emptiness_test::META,
        &paredit_feature_lint_performance::length_emptiness_test::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::quadratic_accumulation::META,
        &paredit_feature_lint_performance::quadratic_accumulation::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::linear_search_in_loop::META,
        &paredit_feature_lint_performance::linear_search_in_loop::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::unnecessary_copy::META,
        &paredit_feature_lint_performance::unnecessary_copy::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::copy_before_destructive::META,
        &paredit_feature_lint_performance::copy_before_destructive::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::loop_invariant_allocation::META,
        &paredit_feature_lint_performance::loop_invariant_allocation::RULE,
    ),
    // What the code assumes about where it runs.
    RuleEntry::new(
        &paredit_feature_lint_portability::implementation_package_symbol::META,
        &paredit_feature_lint_portability::implementation_package_symbol::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::unportable_pathname::META,
        &paredit_feature_lint_portability::unportable_pathname::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::ascii_code_char::META,
        &paredit_feature_lint_portability::ascii_code_char::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::float_equality::META,
        &paredit_feature_lint_portability::float_equality::RULE,
    ),
    // Shared state, untrusted input, leaked resources, swallowed errors: every
    // rule below reports a form whose defect is only visible one level out.
    RuleEntry::new(
        &paredit_feature_lint_safety::global_mutation_in_function::META,
        &paredit_feature_lint_safety::global_mutation_in_function::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::check_then_act::META,
        &paredit_feature_lint_safety::check_then_act::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::eval_of_non_constant::META,
        &paredit_feature_lint_safety::eval_of_non_constant::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::read_without_read_eval_guard::META,
        &paredit_feature_lint_safety::read_without_read_eval_guard::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::subprocess_string_building::META,
        &paredit_feature_lint_safety::subprocess_string_building::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::unclosed_stream::META,
        &paredit_feature_lint_safety::unclosed_stream::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::stream_escapes_with_open_file::META,
        &paredit_feature_lint_safety::stream_escapes_with_open_file::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::handler_case_swallows_error::META,
        &paredit_feature_lint_safety::handler_case_swallows_error::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::unreachable_handler_clause::META,
        &paredit_feature_lint_safety::unreachable_handler_clause::RULE,
    ),
    // What a definition says about itself: its name, its docstring, its
    // declarations, and its CLOS options.
    RuleEntry::new(
        &paredit_feature_lint_convention::definition_naming::META,
        &paredit_feature_lint_convention::definition_naming::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::destructive_function_naming::META,
        &paredit_feature_lint_convention::destructive_function_naming::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::missing_docstring::META,
        &paredit_feature_lint_convention::missing_docstring::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::ignore_declaration_conflict::META,
        &paredit_feature_lint_convention::ignore_declaration_conflict::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::contradictory_optimize::META,
        &paredit_feature_lint_convention::contradictory_optimize::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::defclass_slot_option::META,
        &paredit_feature_lint_convention::defclass_slot_option::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::method_lambda_list_mismatch::META,
        &paredit_feature_lint_convention::method_lambda_list_mismatch::RULE,
    ),
    // Macro hygiene: one rule per risk `inspect macro-hygiene` detects, so
    // that each can be denied, failed on, suppressed and baselined on its own.
    // All but the last declare their own multi-dialect scope rather than the
    // default Common-Lisp-only one, so they also run over Emacs Lisp, Clojure,
    // Janet, Hy, Carp, Fennel and LFE.
    RuleEntry::new(
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::variable_capture::META,
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::variable_capture::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::multiple_evaluation::META,
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::multiple_evaluation::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::parameter_reordering::META,
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::parameter_reordering::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::deep_quasiquote::META,
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::deep_quasiquote::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::missing_declare::META,
        &paredit_feature_lisp_analysis::macro_hygiene_report::rule::missing_declare::RULE,
    ),
    // Emacs Lisp. Every rule below declares `Dialect::EmacsLisp` only, so a
    // Common Lisp run skips them before walking anything.
    RuleEntry::new(
        &paredit_feature_emacs_lisp::missing_lexical_binding::rule::META,
        &paredit_feature_emacs_lisp::missing_lexical_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::unreachable_lexical_binding::rule::META,
        &paredit_feature_emacs_lisp::unreachable_lexical_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::autoload_cookie_without_form::rule::META,
        &paredit_feature_emacs_lisp::autoload_cookie_without_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::defcustom_missing_type::rule::META,
        &paredit_feature_emacs_lisp::defcustom_missing_type::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::defcustom_missing_group::rule::META,
        &paredit_feature_emacs_lisp::defcustom_missing_group::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::obsolete_cl_alias::rule::META,
        &paredit_feature_emacs_lisp::obsolete_cl_alias::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::quoted_lambda::rule::META,
        &paredit_feature_emacs_lisp::quoted_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::interactive_in_macro::rule::META,
        &paredit_feature_emacs_lisp::interactive_in_macro::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_emacs_lisp::condition_case_without_handler::rule::META,
        &paredit_feature_emacs_lisp::condition_case_without_handler::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::embedded_secret::META,
        &paredit_feature_lint_safety::embedded_secret::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::giant_conditional_form::rule::META,
        &paredit_feature_lint_form_shape::giant_conditional_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::effectively_constant_variable::META,
        &paredit_feature_lint_convention::effectively_constant_variable::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::redundant_condition_supertype::META,
        &paredit_feature_lint_convention::redundant_condition_supertype::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_convention::commented_out_code::META,
        &paredit_feature_lint_convention::commented_out_code::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::execution_order_dependency::META,
        &paredit_feature_lint_safety::execution_order_dependency::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::declarative_style_score::META,
        &paredit_feature_lint_safety::declarative_style_score::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::package_level_shadowing::rule::META,
        &paredit_feature_lint_form_shape::package_level_shadowing::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::self_recursive_tail_call::rule::META,
        &paredit_feature_lint_control_flow::self_recursive_tail_call::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::leftover_print_debug::rule::META,
        &paredit_feature_lint_repl_debug::leftover_print_debug::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::leftover_trace_call::rule::META,
        &paredit_feature_lint_repl_debug::leftover_trace_call::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::leftover_break_call::rule::META,
        &paredit_feature_lint_repl_debug::leftover_break_call::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::leftover_inspect_call::rule::META,
        &paredit_feature_lint_repl_debug::leftover_inspect_call::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::leftover_time_benchmark_call::rule::META,
        &paredit_feature_lint_repl_debug::leftover_time_benchmark_call::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::leftover_step_call::rule::META,
        &paredit_feature_lint_repl_debug::leftover_step_call::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::commented_repl_transcript::rule::META,
        &paredit_feature_lint_repl_debug::commented_repl_transcript::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_repl_debug::leftover_format_debug_marker::rule::META,
        &paredit_feature_lint_repl_debug::leftover_format_debug_marker::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::around_method_missing_call_next_method::rule::META,
        &paredit_feature_lint_object_system::around_method_missing_call_next_method::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::defclass_required_slot_no_initform_or_initarg::rule::META,
        &paredit_feature_lint_object_system::defclass_required_slot_no_initform_or_initarg::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::defclass_slot_shadowing::rule::META,
        &paredit_feature_lint_object_system::defclass_slot_shadowing::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::duplicate_defmethod_signature::rule::META,
        &paredit_feature_lint_object_system::duplicate_defmethod_signature::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::generic_function_no_methods::rule::META,
        &paredit_feature_lint_object_system::generic_function_no_methods::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::method_qualifier_typo::rule::META,
        &paredit_feature_lint_object_system::method_qualifier_typo::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::print_object_without_print_unreadable_object::rule::META,
        &paredit_feature_lint_object_system::print_object_without_print_unreadable_object::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_object_system::slot_value_bypasses_accessor::rule::META,
        &paredit_feature_lint_object_system::slot_value_bypasses_accessor::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_system::cerror_missing_continue_format::rule::META,
        &paredit_feature_lint_condition_system::cerror_missing_continue_format::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_depth::condition_type_datum_with_string_initarg::META,
        &paredit_feature_lint_condition_depth::condition_type_datum_with_string_initarg::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_depth::unwind_protect_cleanup_signals::META,
        &paredit_feature_lint_condition_depth::unwind_protect_cleanup_signals::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_lfe_carp_depth::illegal_guard_call::rule::META,
        &paredit_feature_lint_lfe_carp_depth::illegal_guard_call::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_lfe_carp_depth::dead_clause::rule::META,
        &paredit_feature_lint_lfe_carp_depth::dead_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_hy_depth::unreachable_except_clause::rule::META,
        &paredit_feature_lint_hy_depth::unreachable_except_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_depth::fennel_bad_unpack::rule::META,
        &paredit_feature_lint_fennel_janet_depth::fennel_bad_unpack::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_depth::fennel_nested_associative_operator::rule::META,
        &paredit_feature_lint_fennel_janet_depth::fennel_nested_associative_operator::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_depth::fennel_redundant_do::rule::META,
        &paredit_feature_lint_fennel_janet_depth::fennel_redundant_do::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_depth::janet_dead_branch_on_constant_condition::rule::META,
        &paredit_feature_lint_fennel_janet_depth::janet_dead_branch_on_constant_condition::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_depth::janet_unreachable_match_clause::rule::META,
        &paredit_feature_lint_fennel_janet_depth::janet_unreachable_match_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_destructive_sequence::discarded_destructive_sequence_result::META,
        &paredit_feature_lint_destructive_sequence::discarded_destructive_sequence_result::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_system::define_condition_empty_superclass_list::rule::META,
        &paredit_feature_lint_condition_system::define_condition_empty_superclass_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_system::define_condition_missing_report_for_error_type::rule::META,
        &paredit_feature_lint_condition_system::define_condition_missing_report_for_error_type::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_system::handler_bind_handler_returns_bare_value::rule::META,
        &paredit_feature_lint_condition_system::handler_bind_handler_returns_bare_value::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_system::ignore_errors_wraps_non_error_signal::rule::META,
        &paredit_feature_lint_condition_system::ignore_errors_wraps_non_error_signal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_system::restart_case_clause_without_report::rule::META,
        &paredit_feature_lint_condition_system::restart_case_clause_without_report::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_condition_system::signal_on_error_condition_returns_silently::rule::META,
        &paredit_feature_lint_condition_system::signal_on_error_condition_returns_silently::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_iteration_flow::dolist_result_form_references_loop_variable::rule::META,
        &paredit_feature_lint_iteration_flow::dolist_result_form_references_loop_variable::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_iteration_flow::dotimes_bound_mutation_has_no_effect::rule::META,
        &paredit_feature_lint_iteration_flow::dotimes_bound_mutation_has_no_effect::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_iteration_flow::loop_clause_order_violation::rule::META,
        &paredit_feature_lint_iteration_flow::loop_clause_order_violation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_iteration_flow::loop_for_across_statically_known_list::rule::META,
        &paredit_feature_lint_iteration_flow::loop_for_across_statically_known_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_iteration_flow::loop_into_accumulator_kind_conflict::rule::META,
        &paredit_feature_lint_iteration_flow::loop_into_accumulator_kind_conflict::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_iteration_flow::loop_unreachable_finally_clause::rule::META,
        &paredit_feature_lint_iteration_flow::loop_unreachable_finally_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_testing::disabled_test_left_in::rule::META,
        &paredit_feature_lint_testing::disabled_test_left_in::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_testing::duplicate_test_name::rule::META,
        &paredit_feature_lint_testing::duplicate_test_name::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_testing::empty_test_body::rule::META,
        &paredit_feature_lint_testing::empty_test_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_testing::sleep_in_test::rule::META,
        &paredit_feature_lint_testing::sleep_in_test::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_testing::test_asserts_constant::rule::META,
        &paredit_feature_lint_testing::test_asserts_constant::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_testing::test_without_assertion::rule::META,
        &paredit_feature_lint_testing::test_without_assertion::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_concurrency::atom_swap_with_side_effect::rule::META,
        &paredit_feature_lint_concurrency::atom_swap_with_side_effect::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_concurrency::dynamic_var_bound_across_thread_boundary::rule::META,
        &paredit_feature_lint_concurrency::dynamic_var_bound_across_thread_boundary::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_concurrency::future_promise_never_realized::rule::META,
        &paredit_feature_lint_concurrency::future_promise_never_realized::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_concurrency::lock_acquired_not_released::rule::META,
        &paredit_feature_lint_concurrency::lock_acquired_not_released::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_concurrency::recursive_lock_reentry_risk::rule::META,
        &paredit_feature_lint_concurrency::recursive_lock_reentry_risk::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_concurrency::thread_spawned_without_error_handler::rule::META,
        &paredit_feature_lint_concurrency::thread_spawned_without_error_handler::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_concurrency::unsynchronized_shared_mutation::rule::META,
        &paredit_feature_lint_concurrency::unsynchronized_shared_mutation::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_build_system::asdf_perform_without_call_next_method::rule::META,
        &paredit_feature_lint_build_system::asdf_perform_without_call_next_method::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_build_system::asdf_self_referential_depends_on::rule::META,
        &paredit_feature_lint_build_system::asdf_self_referential_depends_on::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_build_system::asdf_system_missing_version::rule::META,
        &paredit_feature_lint_build_system::asdf_system_missing_version::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_build_system::defpackage_without_in_package::rule::META,
        &paredit_feature_lint_build_system::defpackage_without_in_package::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::block_name_shadows_outer_block::rule::META,
        &paredit_feature_lint_control_flow::block_name_shadows_outer_block::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::dotimes_dolist_index_var_mutated::rule::META,
        &paredit_feature_lint_control_flow::dotimes_dolist_index_var_mutated::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::go_to_undefined_tag::rule::META,
        &paredit_feature_lint_control_flow::go_to_undefined_tag::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::multiple_value_bind_all_ignored::rule::META,
        &paredit_feature_lint_control_flow::multiple_value_bind_all_ignored::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::return_from_unmatched_block::rule::META,
        &paredit_feature_lint_control_flow::return_from_unmatched_block::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::return_outside_implicit_nil_block::rule::META,
        &paredit_feature_lint_control_flow::return_outside_implicit_nil_block::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_control_flow::tagbody_unreachable_tag::rule::META,
        &paredit_feature_lint_control_flow::tagbody_unreachable_tag::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::case_key_eql_pitfall::rule::META,
        &paredit_feature_lint_conditional::case_key_eql_pitfall::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::cond_to_case_candidate::rule::META,
        &paredit_feature_lint_conditional::cond_to_case_candidate::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::nested_cond_flattenable::rule::META,
        &paredit_feature_lint_conditional::nested_cond_flattenable::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_conditional::when_unless_implicit_nil_misused::rule::META,
        &paredit_feature_lint_conditional::when_unless_implicit_nil_misused::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::format_tilde_slash_unvalidated_function_designator::META,
        &paredit_feature_lint_safety::format_tilde_slash_unvalidated_function_designator::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::insecure_temp_file_fixed_name_shared_directory::META,
        &paredit_feature_lint_safety::insecure_temp_file_fixed_name_shared_directory::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::path_traversal_via_concatenated_filename::META,
        &paredit_feature_lint_safety::path_traversal_via_concatenated_filename::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::read_eval_star_rebound_to_t::META,
        &paredit_feature_lint_safety::read_eval_star_rebound_to_t::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::sql_query_string_built_via_format::META,
        &paredit_feature_lint_safety::sql_query_string_built_via_format::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_safety::world_writable_file_mode_in_open_call::META,
        &paredit_feature_lint_safety::world_writable_file_mode_in_open_call::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::redundant_full_sequence_traversal_fusable_maps::META,
        &paredit_feature_lint_performance::redundant_full_sequence_traversal_fusable_maps::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::repeated_hash_table_lookup_same_key::META,
        &paredit_feature_lint_performance::repeated_hash_table_lookup_same_key::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_performance::unnecessary_sort_before_extremum_extraction::META,
        &paredit_feature_lint_performance::unnecessary_sort_before_extremum_extraction::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::char_code_limit_loop::META,
        &paredit_feature_lint_portability::char_code_limit_loop::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::namestring_round_trip::META,
        &paredit_feature_lint_portability::namestring_round_trip::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_portability::sort_not_guaranteed_stable::META,
        &paredit_feature_lint_portability::sort_not_guaranteed_stable::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_call_shape::deeply_nested_anonymous_lambda::rule::META,
        &paredit_feature_lint_call_shape::deeply_nested_anonymous_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_call_shape::nested_function_parameter_shadows_enclosing_parameter::rule::META,
        &paredit_feature_lint_call_shape::nested_function_parameter_shadows_enclosing_parameter::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_call_shape::overly_long_parameter_list::rule::META,
        &paredit_feature_lint_call_shape::overly_long_parameter_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_call_shape::positional_argument_count_exceeds_readability::rule::META,
        &paredit_feature_lint_call_shape::positional_argument_count_exceeds_readability::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_call_shape::stringly_typed_dispatch::rule::META,
        &paredit_feature_lint_call_shape::stringly_typed_dispatch::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_documentation::docstring_example_stale_arity::rule::META,
        &paredit_feature_lint_documentation::docstring_example_stale_arity::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_documentation::docstring_summary_line_too_long::rule::META,
        &paredit_feature_lint_documentation::docstring_summary_line_too_long::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_documentation::missing_package_docstring::rule::META,
        &paredit_feature_lint_documentation::missing_package_docstring::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_documentation::todo_fixme_no_attribution::rule::META,
        &paredit_feature_lint_documentation::todo_fixme_no_attribution::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_contract_annotation::clojure_pre_post_vacuous::rule::META,
        &paredit_feature_lint_contract_annotation::clojure_pre_post_vacuous::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_contract_annotation::typed_racket_arity_mismatch::rule::META,
        &paredit_feature_lint_contract_annotation::typed_racket_arity_mismatch::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_introspection::intern_dynamic_package_target::rule::META,
        &paredit_feature_lint_introspection::intern_dynamic_package_target::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_introspection::introspection_probe_unchecked::rule::META,
        &paredit_feature_lint_introspection::introspection_probe_unchecked::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_introspection::symbol_function_fset_dynamic_name::rule::META,
        &paredit_feature_lint_introspection::symbol_function_fset_dynamic_name::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::destructuring_bind_unused_whole::rule::META,
        &paredit_feature_lint_form_shape::destructuring_bind_unused_whole::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::loop_collect_into_immediately_returned::rule::META,
        &paredit_feature_lint_form_shape::loop_collect_into_immediately_returned::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::flet_single_use_inlinable::rule::META,
        &paredit_feature_lint_form_shape::flet_single_use_inlinable::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::multiple_value_setq_arity_mismatch::rule::META,
        &paredit_feature_lint_form_shape::multiple_value_setq_arity_mismatch::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::with_open_file_redundant_direction_default::rule::META,
        &paredit_feature_lint_form_shape::with_open_file_redundant_direction_default::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::ftype_values_arity_mismatch::rule::META,
        &paredit_feature_lint_form_shape::ftype_values_arity_mismatch::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::with_accessors_empty_binding_list::rule::META,
        &paredit_feature_lint_form_shape::with_accessors_empty_binding_list::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_form_shape::quoted_form_contains_stray_unquote::rule::META,
        &paredit_feature_lint_form_shape::quoted_form_contains_stray_unquote::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::hash_table_iteration_order_assumed::rule::META,
        &paredit_feature_lint_sequence::hash_table_iteration_order_assumed::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::set_membership_via_linear_scan::rule::META,
        &paredit_feature_lint_sequence::set_membership_via_linear_scan::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::nested_get_chain::rule::META,
        &paredit_feature_lint_sequence::nested_get_chain::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_sequence::redundant_into_empty_collection::rule::META,
        &paredit_feature_lint_sequence::redundant_into_empty_collection::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::mixed_float_precision_arithmetic::rule::META,
        &paredit_feature_lint_numeric::mixed_float_precision_arithmetic::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::division_result_precision_loss::rule::META,
        &paredit_feature_lint_numeric::division_result_precision_loss::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::epsilon_less_float_loop_bound::rule::META,
        &paredit_feature_lint_numeric::epsilon_less_float_loop_bound::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_numeric::redundant_precision_coercion::rule::META,
        &paredit_feature_lint_numeric::redundant_precision_coercion::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_unknown_directive::rule::META,
        &paredit_feature_lint_string_char::format_unknown_directive::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_percent_ampersand_adjacent_redundancy::rule::META,
        &paredit_feature_lint_string_char::format_percent_ampersand_adjacent_redundancy::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_string_char::format_nested_directive_unbalanced::rule::META,
        &paredit_feature_lint_string_char::format_nested_directive_unbalanced::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_package_hygiene::package_circular_in_package_chain::rule::META,
        &paredit_feature_lint_package_hygiene::package_circular_in_package_chain::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_elisp_idiom::interactive_arity_mismatch::rule::META,
        &paredit_feature_lint_elisp_idiom::interactive_arity_mismatch::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_elisp_idiom::hook_lambda::rule::META,
        &paredit_feature_lint_elisp_idiom::hook_lambda::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_elisp_idiom::save_excursion_set_buffer::rule::META,
        &paredit_feature_lint_elisp_idiom::save_excursion_set_buffer::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_elisp_idiom::require_obsolete_cl::rule::META,
        &paredit_feature_lint_elisp_idiom::require_obsolete_cl::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_pathname_io::pathname_built_by_concatenation::META,
        &paredit_feature_lint_pathname_io::pathname_built_by_concatenation::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_pathname_io::output_stream_without_if_exists::META,
        &paredit_feature_lint_pathname_io::output_stream_without_if_exists::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_pathname_io::pathname_component_compared_case_sensitively::META,
        &paredit_feature_lint_pathname_io::pathname_component_compared_case_sensitively::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_pathname_io::directory_without_wild_component::META,
        &paredit_feature_lint_pathname_io::directory_without_wild_component::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_pathname_io::with_open_file_result_captures_stream::META,
        &paredit_feature_lint_pathname_io::with_open_file_result_captures_stream::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_idiom::with_open_returns_lazy_seq::rule::META,
        &paredit_feature_lint_clojure_idiom::with_open_returns_lazy_seq::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_idiom::def_inside_function_body::rule::META,
        &paredit_feature_lint_clojure_idiom::def_inside_function_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_idiom::single_key_nested_path::rule::META,
        &paredit_feature_lint_clojure_idiom::single_key_nested_path::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_idiom::apply_with_literal_collection::rule::META,
        &paredit_feature_lint_clojure_idiom::apply_with_literal_collection::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_scheme_idiom::begin_single_form::rule::META,
        &paredit_feature_lint_scheme_idiom::begin_single_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_scheme_idiom::let_star_independent_bindings::rule::META,
        &paredit_feature_lint_scheme_idiom::let_star_independent_bindings::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_scheme_idiom::memq_assq_literal_key::rule::META,
        &paredit_feature_lint_scheme_idiom::memq_assq_literal_key::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_scheme_idiom::named_let_never_recurs::rule::META,
        &paredit_feature_lint_scheme_idiom::named_let_never_recurs::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_idiom::var_never_set::rule::META,
        &paredit_feature_lint_fennel_janet_idiom::var_never_set::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_idiom::fennel_deprecated_form::rule::META,
        &paredit_feature_lint_fennel_janet_idiom::fennel_deprecated_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_idiom::fennel_each_over_non_iterator::rule::META,
        &paredit_feature_lint_fennel_janet_idiom::fennel_each_over_non_iterator::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_idiom::janet_empty_loop_body::rule::META,
        &paredit_feature_lint_fennel_janet_idiom::janet_empty_loop_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_fennel_janet_idiom::janet_mutating_immutable_literal::rule::META,
        &paredit_feature_lint_fennel_janet_idiom::janet_mutating_immutable_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_type_declaration::declare_not_at_head_of_body::rule::META,
        &paredit_feature_lint_type_declaration::declare_not_at_head_of_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_type_declaration::declaim_inside_body::rule::META,
        &paredit_feature_lint_type_declaration::declaim_inside_body::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_type_declaration::type_declaration_contradicts_initform::rule::META,
        &paredit_feature_lint_type_declaration::type_declaration_contradicts_initform::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_type_declaration::the_form_with_impossible_type::rule::META,
        &paredit_feature_lint_type_declaration::the_form_with_impossible_type::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_type_declaration::type_declaration_on_rest_parameter::rule::META,
        &paredit_feature_lint_type_declaration::type_declaration_on_rest_parameter::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_compile_time::eval_when_execute_only::rule::META,
        &paredit_feature_lint_compile_time::eval_when_execute_only::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_compile_time::eval_when_body_never_runs::rule::META,
        &paredit_feature_lint_compile_time::eval_when_body_never_runs::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_compile_time::defconstant_non_eql_value::rule::META,
        &paredit_feature_lint_compile_time::defconstant_non_eql_value::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_hy_lfe_idiom::mutable_default_argument::rule::META,
        &paredit_feature_lint_hy_lfe_idiom::mutable_default_argument::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_hy_lfe_idiom::identity_comparison_with_literal::rule::META,
        &paredit_feature_lint_hy_lfe_idiom::identity_comparison_with_literal::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_hy_lfe_idiom::bare_except::rule::META,
        &paredit_feature_lint_hy_lfe_idiom::bare_except::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_hy_lfe_idiom::catch_swallows_exit::rule::META,
        &paredit_feature_lint_hy_lfe_idiom::catch_swallows_exit::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_carp_idiom::deprecated_thread_macro::rule::META,
        &paredit_feature_lint_carp_idiom::deprecated_thread_macro::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_loop_facility::parallel_binding_reads_sibling::rule::META,
        &paredit_feature_lint_loop_facility::parallel_binding_reads_sibling::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_loop_facility::into_accumulator_never_read::rule::META,
        &paredit_feature_lint_loop_facility::into_accumulator_never_read::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_loop_facility::accumulation_discarded_by_finally_return::rule::META,
        &paredit_feature_lint_loop_facility::accumulation_discarded_by_finally_return::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_generic_dispatch::defgeneric_method_option_incongruent::rule::META,
        &paredit_feature_lint_generic_dispatch::defgeneric_method_option_incongruent::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_generic_dispatch::initialization_primary_without_call_next_method::rule::META,
        &paredit_feature_lint_generic_dispatch::initialization_primary_without_call_next_method::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_generic_dispatch::class_allocated_slot_with_initarg::rule::META,
        &paredit_feature_lint_generic_dispatch::class_allocated_slot_with_initarg::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_binding_analysis::unused_local_binding::rule::META,
        &paredit_feature_lint_binding_analysis::unused_local_binding::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_data_structure::defstruct_boa_aux_uninitialized_slot::rule::META,
        &paredit_feature_lint_data_structure::defstruct_boa_aux_uninitialized_slot::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_data_structure::defstruct_include_type_mismatch::rule::META,
        &paredit_feature_lint_data_structure::defstruct_include_type_mismatch::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_data_structure::hash_table_literal_string_key_under_eql::rule::META,
        &paredit_feature_lint_data_structure::hash_table_literal_string_key_under_eql::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_data_structure::make_array_conflicting_initializers::rule::META,
        &paredit_feature_lint_data_structure::make_array_conflicting_initializers::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_data_structure::maphash_mutates_other_entry::rule::META,
        &paredit_feature_lint_data_structure::maphash_mutates_other_entry::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_data_structure::vector_push_without_fill_pointer::rule::META,
        &paredit_feature_lint_data_structure::vector_push_without_fill_pointer::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_racket_depth::match_unreachable_clause::rule::META,
        &paredit_feature_lint_racket_depth::match_unreachable_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_racket_depth::for_comprehension_value_discarded::rule::META,
        &paredit_feature_lint_racket_depth::for_comprehension_value_discarded::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_racket_depth::begin0_single_form::rule::META,
        &paredit_feature_lint_racket_depth::begin0_single_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_racket_depth::case_lambda_single_clause::rule::META,
        &paredit_feature_lint_racket_depth::case_lambda_single_clause::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_racket_depth::parameterize_empty_bindings::rule::META,
        &paredit_feature_lint_racket_depth::parameterize_empty_bindings::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_elisp_depth::process_filter_assumes_whole_output::rule::META,
        &paredit_feature_lint_elisp_depth::process_filter_assumes_whole_output::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_elisp_depth::repeating_timer_handle_discarded::rule::META,
        &paredit_feature_lint_elisp_depth::repeating_timer_handle_discarded::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_depth::go_block_blocking_channel_op::rule::META,
        &paredit_feature_lint_clojure_depth::go_block_blocking_channel_op::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_depth::parking_op_outside_go_machinery::rule::META,
        &paredit_feature_lint_clojure_depth::parking_op_outside_go_machinery::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_depth::contains_on_non_associative::rule::META,
        &paredit_feature_lint_clojure_depth::contains_on_non_associative::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_clojure_depth::reference_type_operator_mismatch::rule::META,
        &paredit_feature_lint_clojure_depth::reference_type_operator_mismatch::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_macro_authoring::macro_body_destroys_argument_form::rule::META,
        &paredit_feature_lint_macro_authoring::macro_body_destroys_argument_form::rule::RULE,
    ),
    RuleEntry::new(
        &paredit_feature_lint_macro_authoring::macrolet_expander_captures_lexical_variable::rule::META,
        &paredit_feature_lint_macro_authoring::macrolet_expander_captures_lexical_variable::rule::RULE,
    ),
];
